# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TweetCreateRequestPoll")

model_instance <- TweetCreateRequestPoll$new()

test_that("duration_minutes", {
  # tests for the property `duration_minutes` (integer)
  # Duration of the poll in minutes.

  # uncomment below to test the property
  # expect_equal(model.instance$`duration_minutes`, "EXPECTED_RESULT")
})

test_that("options", {
  # tests for the property `options` (array[character])

  # uncomment below to test the property
  # expect_equal(model.instance$`options`, "EXPECTED_RESULT")
})

test_that("reply_settings", {
  # tests for the property `reply_settings` (character)
  # Settings to indicate who can reply to the Tweet.

  # uncomment below to test the property
  # expect_equal(model.instance$`reply_settings`, "EXPECTED_RESULT")
})
