# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BlockUserRequest")

model_instance <- BlockUserRequest$new()

test_that("target_user_id", {
  # tests for the property `target_user_id` (character)
  # Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.

  # uncomment below to test the property
  #expect_equal(model.instance$`target_user_id`, "EXPECTED_RESULT")
})
