# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TweetComplianceSchemaTweet")

model_instance <- TweetComplianceSchemaTweet$new()

test_that("author_id", {
  # tests for the property `author_id` (character)
  # Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.

  # uncomment below to test the property
  # expect_equal(model.instance$`author_id`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)
  # Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.

  # uncomment below to test the property
  # expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})
