# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TweetGeo")

model_instance <- TweetGeo$new()

test_that("coordinates", {
  # tests for the property `coordinates` (Point)

  # uncomment below to test the property
  # expect_equal(model.instance$`coordinates`, "EXPECTED_RESULT")
})

test_that("place_id", {
  # tests for the property `place_id` (character)
  # The identifier for this place.

  # uncomment below to test the property
  # expect_equal(model.instance$`place_id`, "EXPECTED_RESULT")
})
