# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FilteredStreamingTweetResponseMatchingRulesInner")

model_instance <- FilteredStreamingTweetResponseMatchingRulesInner$new()

test_that("id", {
  # tests for the property `id` (character)
  # Unique identifier of this rule.

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("tag", {
  # tests for the property `tag` (character)
  # A tag meant for the labeling of user provided rules.

  # uncomment below to test the property
  #expect_equal(model.instance$`tag`, "EXPECTED_RESULT")
})
