# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FullTextEntitiesAnnotationsInner")

model_instance <- FullTextEntitiesAnnotationsInner$new()

test_that("end", {
  # tests for the property `end` (integer)
  # Index (zero-based) at which position this entity ends.  The index is inclusive.

  # uncomment below to test the property
  # expect_equal(model.instance$`end`, "EXPECTED_RESULT")
})

test_that("start", {
  # tests for the property `start` (integer)
  # Index (zero-based) at which position this entity starts.  The index is inclusive.

  # uncomment below to test the property
  # expect_equal(model.instance$`start`, "EXPECTED_RESULT")
})

test_that("normalized_text", {
  # tests for the property `normalized_text` (character)
  # Text used to determine annotation.

  # uncomment below to test the property
  # expect_equal(model.instance$`normalized_text`, "EXPECTED_RESULT")
})

test_that("probability", {
  # tests for the property `probability` (numeric)
  # Confidence factor for annotation type.

  # uncomment below to test the property
  # expect_equal(model.instance$`probability`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # Annotation type.

  # uncomment below to test the property
  # expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})
