# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PollOption")

model_instance <- PollOption$new()

test_that("label", {
  # tests for the property `label` (character)
  # The text of a poll choice.

  # uncomment below to test the property
  # expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("position", {
  # tests for the property `position` (integer)
  # Position of this choice in the poll.

  # uncomment below to test the property
  # expect_equal(model.instance$`position`, "EXPECTED_RESULT")
})

test_that("votes", {
  # tests for the property `votes` (integer)
  # Number of users who voted for this choice.

  # uncomment below to test the property
  # expect_equal(model.instance$`votes`, "EXPECTED_RESULT")
})
