# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ComplianceApi")

api_instance <- ComplianceApi$new()

test_that("create_batch_compliance_job", {
  # tests for create_batch_compliance_job
  # base path: https://api.twitter.com
  # Create compliance job
  # Creates a compliance for the given job type
  # @param create_compliance_job_request CreateComplianceJobRequest
  # @return [CreateComplianceJobResponse]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("get_batch_compliance_job", {
  # tests for get_batch_compliance_job
  # base path: https://api.twitter.com
  # Get Compliance Job
  # Returns a single Compliance Job by ID
  # @param id character The ID of the Compliance Job to retrieve.
  # @param compliance_job_fields set[character] A comma separated list of ComplianceJob fields to display. (optional)
  # @return [Get2ComplianceJobsIdResponse]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("get_tweets_compliance_stream", {
  # tests for get_tweets_compliance_stream
  # base path: https://api.twitter.com
  # Tweets Compliance stream
  # Streams 100% of compliance data for Tweets
  # @param partition integer The partition number.
  # @param backfill_minutes integer The number of minutes of backfill requested. (optional)
  # @param start_time character YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the Tweet Compliance events will be provided. (optional)
  # @param end_time character YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Tweet Compliance events will be provided. (optional)
  # @return [TweetComplianceStreamResponse]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("get_users_compliance_stream", {
  # tests for get_users_compliance_stream
  # base path: https://api.twitter.com
  # Users Compliance stream
  # Streams 100% of compliance data for Users
  # @param partition integer The partition number.
  # @param backfill_minutes integer The number of minutes of backfill requested. (optional)
  # @param start_time character YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the User Compliance events will be provided. (optional)
  # @param end_time character YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp from which the User Compliance events will be provided. (optional)
  # @return [UserComplianceStreamResponse]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})

test_that("list_batch_compliance_jobs", {
  # tests for list_batch_compliance_jobs
  # base path: https://api.twitter.com
  # List Compliance Jobs
  # Returns recent Compliance Jobs for a given job type and optional job status
  # @param type character Type of Compliance Job to list.
  # @param status character Status of Compliance Job to list. (optional)
  # @param compliance_job_fields set[character] A comma separated list of ComplianceJob fields to display. (optional)
  # @return [Get2ComplianceJobsResponse]

  # uncomment below to test the operation
  # expect_equal(result, "EXPECTED_RESULT")
})
