# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserWithheld")

model_instance <- UserWithheld$new()

test_that("country_codes", {
  # tests for the property `country_codes` (set[character])
  # Provides a list of countries where this content is not available.

  # uncomment below to test the property
  # expect_equal(model.instance$`country_codes`, "EXPECTED_RESULT")
})

test_that("scope", {
  # tests for the property `scope` (character)
  # Indicates that the content being withheld is a &#x60;user&#x60;.

  # uncomment below to test the property
  # expect_equal(model.instance$`scope`, "EXPECTED_RESULT")
})
