# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserEntities")

model_instance <- UserEntities$new()

test_that("description", {
  # tests for the property `description` (FullTextEntities)

  # uncomment below to test the property
  # expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (UserEntitiesUrl)

  # uncomment below to test the property
  # expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})
