# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TweetCreateResponseData")

model_instance <- TweetCreateResponseData$new()

test_that("id", {
  # tests for the property `id` (character)
  # Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.

  # uncomment below to test the property
  # expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("text", {
  # tests for the property `text` (character)
  # The content of the Tweet.

  # uncomment below to test the property
  # expect_equal(model.instance$`text`, "EXPECTED_RESULT")
})
