# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TweetDropComplianceSchema")

model_instance <- TweetDropComplianceSchema$new()

test_that("drop", {
  # tests for the property `drop` (TweetComplianceSchema)

  # uncomment below to test the property
  # expect_equal(model.instance$`drop`, "EXPECTED_RESULT")
})
