# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TweetDeleteComplianceSchema")

model_instance <- TweetDeleteComplianceSchema$new()

test_that("delete", {
  # tests for the property `delete` (TweetComplianceSchema)

  # uncomment below to test the property
  # expect_equal(model.instance$`delete`, "EXPECTED_RESULT")
})
