# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Get2TweetsSampleStreamResponse")

model_instance <- Get2TweetsSampleStreamResponse$new()

test_that("data", {
  # tests for the property `data` (Tweet)

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

test_that("errors", {
  # tests for the property `errors` (array[Problem])

  # uncomment below to test the property
  #expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})

test_that("includes", {
  # tests for the property `includes` (Expansions)

  # uncomment below to test the property
  #expect_equal(model.instance$`includes`, "EXPECTED_RESULT")
})
