# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TweetCreateRequestReply")

model_instance <- TweetCreateRequestReply$new()

test_that("exclude_reply_user_ids", {
  # tests for the property `exclude_reply_user_ids` (array[character])
  # A list of User Ids to be excluded from the reply Tweet.

  # uncomment below to test the property
  # expect_equal(model.instance$`exclude_reply_user_ids`, "EXPECTED_RESULT")
})

test_that("in_reply_to_tweet_id", {
  # tests for the property `in_reply_to_tweet_id` (character)
  # Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.

  # uncomment below to test the property
  # expect_equal(model.instance$`in_reply_to_tweet_id`, "EXPECTED_RESULT")
})
