# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BlockUserMutationResponse")

model_instance <- BlockUserMutationResponse$new()

test_that("data", {
  # tests for the property `data` (BlockUserMutationResponseData)

  # uncomment below to test the property
  # expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

test_that("errors", {
  # tests for the property `errors` (array[Problem])

  # uncomment below to test the property
  # expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})
