# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserPublicMetrics")

model_instance <- UserPublicMetrics$new()

test_that("followers_count", {
  # tests for the property `followers_count` (integer)
  # Number of Users who are following this User.

  # uncomment below to test the property
  #expect_equal(model.instance$`followers_count`, "EXPECTED_RESULT")
})

test_that("following_count", {
  # tests for the property `following_count` (integer)
  # Number of Users this User is following.

  # uncomment below to test the property
  #expect_equal(model.instance$`following_count`, "EXPECTED_RESULT")
})

test_that("listed_count", {
  # tests for the property `listed_count` (integer)
  # The number of lists that include this User.

  # uncomment below to test the property
  #expect_equal(model.instance$`listed_count`, "EXPECTED_RESULT")
})

test_that("tweet_count", {
  # tests for the property `tweet_count` (integer)
  # The number of Tweets (including Retweets) posted by this User.

  # uncomment below to test the property
  #expect_equal(model.instance$`tweet_count`, "EXPECTED_RESULT")
})
