# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DisallowedResourceProblemAllOf")

model_instance <- DisallowedResourceProblemAllOf$new()

test_that("resource_id", {
  # tests for the property `resource_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`resource_id`, "EXPECTED_RESULT")
})

test_that("resource_type", {
  # tests for the property `resource_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`resource_type`, "EXPECTED_RESULT")
})

test_that("section", {
  # tests for the property `section` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`section`, "EXPECTED_RESULT")
})
