# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AnimatedGifAllOf")

model_instance <- AnimatedGifAllOf$new()

test_that("preview_image_url", {
  # tests for the property `preview_image_url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`preview_image_url`, "EXPECTED_RESULT")
})

test_that("variants", {
  # tests for the property `variants` (array[Variant])
  # An array of all available variants of the media.

  # uncomment below to test the property
  #expect_equal(model.instance$`variants`, "EXPECTED_RESULT")
})
