# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RulesLookupResponse")

model_instance <- RulesLookupResponse$new()

test_that("data", {
  # tests for the property `data` (array[Rule])

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

test_that("meta", {
  # tests for the property `meta` (RulesResponseMetadata)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta`, "EXPECTED_RESULT")
})
