# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TweetPublicMetrics")

model_instance <- TweetPublicMetrics$new()

test_that("like_count", {
  # tests for the property `like_count` (integer)
  # Number of times this Tweet has been liked.

  # uncomment below to test the property
  #expect_equal(model.instance$`like_count`, "EXPECTED_RESULT")
})

test_that("quote_count", {
  # tests for the property `quote_count` (integer)
  # Number of times this Tweet has been quoted.

  # uncomment below to test the property
  #expect_equal(model.instance$`quote_count`, "EXPECTED_RESULT")
})

test_that("reply_count", {
  # tests for the property `reply_count` (integer)
  # Number of times this Tweet has been replied to.

  # uncomment below to test the property
  #expect_equal(model.instance$`reply_count`, "EXPECTED_RESULT")
})

test_that("retweet_count", {
  # tests for the property `retweet_count` (integer)
  # Number of times this Tweet has been Retweeted.

  # uncomment below to test the property
  #expect_equal(model.instance$`retweet_count`, "EXPECTED_RESULT")
})
