# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MuteUserMutationResponseData")

model_instance <- MuteUserMutationResponseData$new()

test_that("muting", {
  # tests for the property `muting` (character)

  # uncomment below to test the property
  # expect_equal(model.instance$`muting`, "EXPECTED_RESULT")
})
