# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ListDeleteResponseData")

model_instance <- ListDeleteResponseData$new()

test_that("deleted", {
  # tests for the property `deleted` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`deleted`, "EXPECTED_RESULT")
})
