# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Get2ComplianceJobsResponseMeta")

model_instance <- Get2ComplianceJobsResponseMeta$new()

test_that("result_count", {
  # tests for the property `result_count` (integer)
  # The number of results returned in this response.

  # uncomment below to test the property
  # expect_equal(model.instance$`result_count`, "EXPECTED_RESULT")
})
