# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MentionEntity")

model_instance <- MentionEntity$new()

test_that("end", {
  # tests for the property `end` (integer)
  # Index (zero-based) at which position this entity ends.  The index is exclusive.

  # uncomment below to test the property
  #expect_equal(model.instance$`end`, "EXPECTED_RESULT")
})

test_that("start", {
  # tests for the property `start` (integer)
  # Index (zero-based) at which position this entity starts.  The index is inclusive.

  # uncomment below to test the property
  #expect_equal(model.instance$`start`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)
  # Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("username", {
  # tests for the property `username` (character)
  # The Twitter handle (screen name) of this user.

  # uncomment below to test the property
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})
