# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TweetsApi")

api_instance <- TweetsApi$new()

test_that("add_or_delete_rules", {
  # tests for add_or_delete_rules
  # base path: https://api.twitter.com
  # Add/Delete rules
  # Add or delete rules from a User&#39;s active rule set. Users can provide unique, optionally tagged rules to add. Users can delete their entire rule set or a subset specified by rule ids or values.
  # @param add_or_delete_rules_request AddOrDeleteRulesRequest 
  # @param dry_run character Dry Run can be used with both the add and delete action, with the expected result given, but without actually taking any action in the system (meaning the end state will always be as it was when the request was submitted). This is particularly useful to validate rule changes. (optional)
  # @return [AddOrDeleteRulesResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("create_tweet", {
  # tests for create_tweet
  # base path: https://api.twitter.com
  # Creation of a Tweet
  # Causes the User to create a Tweet under the authorized account.
  # @param tweet_create_request TweetCreateRequest 
  # @return [TweetCreateResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("delete_tweet_by_id", {
  # tests for delete_tweet_by_id
  # base path: https://api.twitter.com
  # Tweet delete by Tweet ID
  # Delete specified Tweet (in the path) by ID.
  # @param id character The ID of the Tweet to be deleted.
  # @return [TweetDeleteResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("find_tweet_by_id", {
  # tests for find_tweet_by_id
  # base path: https://api.twitter.com
  # Tweet lookup by Tweet ID
  # Returns a variety of information about the Tweet specified by the requested ID.
  # @param id character A single Tweet ID.
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [Get2TweetsIdResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("find_tweets_by_id", {
  # tests for find_tweets_by_id
  # base path: https://api.twitter.com
  # Tweet lookup by Tweet IDs
  # Returns a variety of information about the Tweet specified by the requested ID.
  # @param ids array[character] A comma separated list of Tweet IDs. Up to 100 are allowed in a single request.
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [Get2TweetsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("find_tweets_that_quote_a_tweet", {
  # tests for find_tweets_that_quote_a_tweet
  # base path: https://api.twitter.com
  # Retrieve Tweets that quote a Tweet.
  # Returns a variety of information about each Tweet that quotes the Tweet specified by the requested ID.
  # @param id character A single Tweet ID.
  # @param max_results integer The maximum number of results to be returned. (optional)
  # @param pagination_token character This parameter is used to get a specified 'page' of results. (optional)
  # @param exclude set[character] The set of entities to exclude (e.g. 'replies' or 'retweets'). (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [Get2TweetsIdQuoteTweetsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("get_rules", {
  # tests for get_rules
  # base path: https://api.twitter.com
  # Rules lookup
  # Returns rules from a User&#39;s active rule set. Users can fetch all of their rules or a subset, specified by the provided rule ids.
  # @param ids array[character] A comma-separated list of Rule IDs. (optional)
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This value is populated by passing the 'next_token' returned in a request to paginate through results. (optional)
  # @return [RulesLookupResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("get_tweets_firehose_stream", {
  # tests for get_tweets_firehose_stream
  # base path: https://api.twitter.com
  # Firehose stream
  # Streams 100% of public Tweets.
  # @param partition integer The partition number.
  # @param backfill_minutes integer The number of minutes of backfill requested. (optional)
  # @param start_time character YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp to which the Tweets will be provided. (optional)
  # @param end_time character YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Tweets will be provided. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [StreamingTweetResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("get_tweets_sample10_stream", {
  # tests for get_tweets_sample10_stream
  # base path: https://api.twitter.com
  # Sample 10% stream
  # Streams a deterministic 10% of public Tweets.
  # @param partition integer The partition number.
  # @param backfill_minutes integer The number of minutes of backfill requested. (optional)
  # @param start_time character YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp to which the Tweets will be provided. (optional)
  # @param end_time character YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Tweets will be provided. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [Get2TweetsSample10StreamResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("hide_reply_by_id", {
  # tests for hide_reply_by_id
  # base path: https://api.twitter.com
  # Hide replies
  # Hides or unhides a reply to an owned conversation.
  # @param tweet_id character The ID of the reply that you want to hide or unhide.
  # @param tweet_hide_request TweetHideRequest  (optional)
  # @return [TweetHideResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("lists_id_tweets", {
  # tests for lists_id_tweets
  # base path: https://api.twitter.com
  # List Tweets timeline by List ID.
  # Returns a list of Tweets associated with the provided List ID.
  # @param id character The ID of the List.
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This parameter is used to get the next 'page' of results. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [Get2ListsIdTweetsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("sample_stream", {
  # tests for sample_stream
  # base path: https://api.twitter.com
  # Sample stream
  # Streams a deterministic 1% of public Tweets.
  # @param backfill_minutes integer The number of minutes of backfill requested. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [StreamingTweetResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("search_stream", {
  # tests for search_stream
  # base path: https://api.twitter.com
  # Filtered stream
  # Streams Tweets matching the stream&#39;s active rule set.
  # @param backfill_minutes integer The number of minutes of backfill requested. (optional)
  # @param start_time character YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the Tweets will be provided. (optional)
  # @param end_time character YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Tweets will be provided. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [FilteredStreamingTweetResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("space_buyers", {
  # tests for space_buyers
  # base path: https://api.twitter.com
  # Retrieve the list of Users who purchased a ticket to the given space
  # Retrieves the list of Users who purchased a ticket to the given space
  # @param id character The ID of the Space to be retrieved.
  # @param pagination_token character This parameter is used to get a specified 'page' of results. (optional)
  # @param max_results integer The maximum number of results. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2SpacesIdBuyersResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("space_tweets", {
  # tests for space_tweets
  # base path: https://api.twitter.com
  # Retrieve Tweets from a Space.
  # Retrieves Tweets shared in the specified Space.
  # @param id character The ID of the Space to be retrieved.
  # @param max_results integer The number of Tweets to fetch from the provided space. If not provided, the value will default to the maximum of 100. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [Get2SpacesIdTweetsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("tweet_counts_full_archive_search", {
  # tests for tweet_counts_full_archive_search
  # base path: https://api.twitter.com
  # Full archive search counts
  # Returns Tweet Counts that match a search query.
  # @param query character One query/rule/filter for matching Tweets. Refer to https://t.co/rulelength to identify the max query length.
  # @param start_time character YYYY-MM-DDTHH:mm:ssZ. The oldest UTC timestamp (from most recent 7 days) from which the Tweets will be provided. Timestamp is in second granularity and is inclusive (i.e. 12:00:01 includes the first second of the minute). (optional)
  # @param end_time character YYYY-MM-DDTHH:mm:ssZ. The newest, most recent UTC timestamp to which the Tweets will be provided. Timestamp is in second granularity and is exclusive (i.e. 12:00:01 excludes the first second of the minute). (optional)
  # @param since_id character Returns results with a Tweet ID greater than (that is, more recent than) the specified ID. (optional)
  # @param until_id character Returns results with a Tweet ID less than (that is, older than) the specified ID. (optional)
  # @param next_token character This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified. (optional)
  # @param pagination_token character This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified. (optional)
  # @param granularity character The granularity for the search counts results. (optional)
  # @param search_count_fields set[character] A comma separated list of SearchCount fields to display. (optional)
  # @return [Get2TweetsCountsAllResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("tweet_counts_recent_search", {
  # tests for tweet_counts_recent_search
  # base path: https://api.twitter.com
  # Recent search counts
  # Returns Tweet Counts from the last 7 days that match a search query.
  # @param query character One query/rule/filter for matching Tweets. Refer to https://t.co/rulelength to identify the max query length.
  # @param start_time character YYYY-MM-DDTHH:mm:ssZ. The oldest UTC timestamp (from most recent 7 days) from which the Tweets will be provided. Timestamp is in second granularity and is inclusive (i.e. 12:00:01 includes the first second of the minute). (optional)
  # @param end_time character YYYY-MM-DDTHH:mm:ssZ. The newest, most recent UTC timestamp to which the Tweets will be provided. Timestamp is in second granularity and is exclusive (i.e. 12:00:01 excludes the first second of the minute). (optional)
  # @param since_id character Returns results with a Tweet ID greater than (that is, more recent than) the specified ID. (optional)
  # @param until_id character Returns results with a Tweet ID less than (that is, older than) the specified ID. (optional)
  # @param next_token character This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified. (optional)
  # @param pagination_token character This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified. (optional)
  # @param granularity character The granularity for the search counts results. (optional)
  # @param search_count_fields set[character] A comma separated list of SearchCount fields to display. (optional)
  # @return [Get2TweetsCountsRecentResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("tweets_fullarchive_search", {
  # tests for tweets_fullarchive_search
  # base path: https://api.twitter.com
  # Full-archive search
  # Returns Tweets that match a search query.
  # @param query character One query/rule/filter for matching Tweets. Refer to https://t.co/rulelength to identify the max query length.
  # @param start_time character YYYY-MM-DDTHH:mm:ssZ. The oldest UTC timestamp from which the Tweets will be provided. Timestamp is in second granularity and is inclusive (i.e. 12:00:01 includes the first second of the minute). (optional)
  # @param end_time character YYYY-MM-DDTHH:mm:ssZ. The newest, most recent UTC timestamp to which the Tweets will be provided. Timestamp is in second granularity and is exclusive (i.e. 12:00:01 excludes the first second of the minute). (optional)
  # @param since_id character Returns results with a Tweet ID greater than (that is, more recent than) the specified ID. (optional)
  # @param until_id character Returns results with a Tweet ID less than (that is, older than) the specified ID. (optional)
  # @param max_results integer The maximum number of search results to be returned by a request. (optional)
  # @param next_token character This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified. (optional)
  # @param pagination_token character This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified. (optional)
  # @param sort_order character This order in which to return results. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [Get2TweetsSearchAllResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("tweets_recent_search", {
  # tests for tweets_recent_search
  # base path: https://api.twitter.com
  # Recent search
  # Returns Tweets from the last 7 days that match a search query.
  # @param query character One query/rule/filter for matching Tweets. Refer to https://t.co/rulelength to identify the max query length.
  # @param start_time character YYYY-MM-DDTHH:mm:ssZ. The oldest UTC timestamp from which the Tweets will be provided. Timestamp is in second granularity and is inclusive (i.e. 12:00:01 includes the first second of the minute). (optional)
  # @param end_time character YYYY-MM-DDTHH:mm:ssZ. The newest, most recent UTC timestamp to which the Tweets will be provided. Timestamp is in second granularity and is exclusive (i.e. 12:00:01 excludes the first second of the minute). (optional)
  # @param since_id character Returns results with a Tweet ID greater than (that is, more recent than) the specified ID. (optional)
  # @param until_id character Returns results with a Tweet ID less than (that is, older than) the specified ID. (optional)
  # @param max_results integer The maximum number of search results to be returned by a request. (optional)
  # @param next_token character This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified. (optional)
  # @param pagination_token character This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified. (optional)
  # @param sort_order character This order in which to return results. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [Get2TweetsSearchRecentResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_like", {
  # tests for users_id_like
  # base path: https://api.twitter.com
  # Causes the User (in the path) to like the specified Tweet
  # Causes the User (in the path) to like the specified Tweet. The User in the path must match the User context authorizing the request.
  # @param id character The ID of the authenticated source User that is requesting to like the Tweet.
  # @param users_likes_create_request UsersLikesCreateRequest  (optional)
  # @return [UsersLikesCreateResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_liked_tweets", {
  # tests for users_id_liked_tweets
  # base path: https://api.twitter.com
  # Returns Tweet objects liked by the provided User ID
  # Returns a list of Tweets liked by the provided User ID
  # @param id character The ID of the User to lookup.
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This parameter is used to get the next 'page' of results. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [Get2UsersIdLikedTweetsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_mentions", {
  # tests for users_id_mentions
  # base path: https://api.twitter.com
  # User mention timeline by User ID
  # Returns Tweet objects that mention username associated to the provided User ID
  # @param id character The ID of the User to lookup.
  # @param since_id character The minimum Tweet ID to be included in the result set. This parameter takes precedence over start_time if both are specified. (optional)
  # @param until_id character The maximum Tweet ID to be included in the result set. This parameter takes precedence over end_time if both are specified. (optional)
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This parameter is used to get the next 'page' of results. (optional)
  # @param start_time character YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the Tweets will be provided. The since_id parameter takes precedence if it is also specified. (optional)
  # @param end_time character YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Tweets will be provided. The until_id parameter takes precedence if it is also specified. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [Get2UsersIdMentionsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_retweets", {
  # tests for users_id_retweets
  # base path: https://api.twitter.com
  # Causes the User (in the path) to retweet the specified Tweet.
  # Causes the User (in the path) to retweet the specified Tweet. The User in the path must match the User context authorizing the request.
  # @param id character The ID of the authenticated source User that is requesting to retweet the Tweet.
  # @param users_retweets_create_request UsersRetweetsCreateRequest  (optional)
  # @return [UsersRetweetsCreateResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_timeline", {
  # tests for users_id_timeline
  # base path: https://api.twitter.com
  # User home timeline by User ID
  # Returns Tweet objects that appears in the provided User ID&#39;s home timeline
  # @param id character The ID of the authenticated source User to list Reverse Chronological Timeline Tweets of.
  # @param since_id character The minimum Tweet ID to be included in the result set. This parameter takes precedence over start_time if both are specified. (optional)
  # @param until_id character The maximum Tweet ID to be included in the result set. This parameter takes precedence over end_time if both are specified. (optional)
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This parameter is used to get the next 'page' of results. (optional)
  # @param exclude set[character] The set of entities to exclude (e.g. 'replies' or 'retweets'). (optional)
  # @param start_time character YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the Tweets will be provided. The since_id parameter takes precedence if it is also specified. (optional)
  # @param end_time character YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Tweets will be provided. The until_id parameter takes precedence if it is also specified. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [Get2UsersIdTimelinesReverseChronologicalResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_tweets", {
  # tests for users_id_tweets
  # base path: https://api.twitter.com
  # User Tweets timeline by User ID
  # Returns a list of Tweets authored by the provided User ID
  # @param id character The ID of the User to lookup.
  # @param since_id character The minimum Tweet ID to be included in the result set. This parameter takes precedence over start_time if both are specified. (optional)
  # @param until_id character The maximum Tweet ID to be included in the result set. This parameter takes precedence over end_time if both are specified. (optional)
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This parameter is used to get the next 'page' of results. (optional)
  # @param exclude set[character] The set of entities to exclude (e.g. 'replies' or 'retweets'). (optional)
  # @param start_time character YYYY-MM-DDTHH:mm:ssZ. The earliest UTC timestamp from which the Tweets will be provided. The since_id parameter takes precedence if it is also specified. (optional)
  # @param end_time character YYYY-MM-DDTHH:mm:ssZ. The latest UTC timestamp to which the Tweets will be provided. The until_id parameter takes precedence if it is also specified. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param media_fields set[character] A comma separated list of Media fields to display. (optional)
  # @param poll_fields set[character] A comma separated list of Poll fields to display. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param place_fields set[character] A comma separated list of Place fields to display. (optional)
  # @return [Get2UsersIdTweetsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_unlike", {
  # tests for users_id_unlike
  # base path: https://api.twitter.com
  # Causes the User (in the path) to unlike the specified Tweet
  # Causes the User (in the path) to unlike the specified Tweet. The User must match the User context authorizing the request
  # @param id character The ID of the authenticated source User that is requesting to unlike the Tweet.
  # @param tweet_id character The ID of the Tweet that the User is requesting to unlike.
  # @return [UsersLikesDeleteResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_unretweets", {
  # tests for users_id_unretweets
  # base path: https://api.twitter.com
  # Causes the User (in the path) to unretweet the specified Tweet
  # Causes the User (in the path) to unretweet the specified Tweet. The User must match the User context authorizing the request
  # @param id character The ID of the authenticated source User that is requesting to retweet the Tweet.
  # @param source_tweet_id character The ID of the Tweet that the User is requesting to unretweet.
  # @return [UsersRetweetsDeleteResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
