# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Variant")

model_instance <- Variant$new()

test_that("bit_rate", {
  # tests for the property `bit_rate` (integer)
  # The bit rate of the media.

  # uncomment below to test the property
  #expect_equal(model.instance$`bit_rate`, "EXPECTED_RESULT")
})

test_that("content_type", {
  # tests for the property `content_type` (character)
  # The content type of the media.

  # uncomment below to test the property
  #expect_equal(model.instance$`content_type`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)
  # The url to the media.

  # uncomment below to test the property
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})
