# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Space")

model_instance <- Space$new()

test_that("created_at", {
  # tests for the property `created_at` (character)
  # Creation time of the Space.

  # uncomment below to test the property
  # expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})

test_that("creator_id", {
  # tests for the property `creator_id` (character)
  # Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.

  # uncomment below to test the property
  # expect_equal(model.instance$`creator_id`, "EXPECTED_RESULT")
})

test_that("ended_at", {
  # tests for the property `ended_at` (character)
  # End time of the Space.

  # uncomment below to test the property
  # expect_equal(model.instance$`ended_at`, "EXPECTED_RESULT")
})

test_that("host_ids", {
  # tests for the property `host_ids` (array[character])
  # The user ids for the hosts of the Space.

  # uncomment below to test the property
  # expect_equal(model.instance$`host_ids`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)
  # The unique identifier of this Space.

  # uncomment below to test the property
  # expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("invited_user_ids", {
  # tests for the property `invited_user_ids` (array[character])
  # An array of user ids for people who were invited to a Space.

  # uncomment below to test the property
  # expect_equal(model.instance$`invited_user_ids`, "EXPECTED_RESULT")
})

test_that("is_ticketed", {
  # tests for the property `is_ticketed` (character)
  # Denotes if the Space is a ticketed Space.

  # uncomment below to test the property
  # expect_equal(model.instance$`is_ticketed`, "EXPECTED_RESULT")
})

test_that("lang", {
  # tests for the property `lang` (character)
  # The language of the Space.

  # uncomment below to test the property
  # expect_equal(model.instance$`lang`, "EXPECTED_RESULT")
})

test_that("participant_count", {
  # tests for the property `participant_count` (integer)
  # The number of participants in a Space.

  # uncomment below to test the property
  # expect_equal(model.instance$`participant_count`, "EXPECTED_RESULT")
})

test_that("scheduled_start", {
  # tests for the property `scheduled_start` (character)
  # A date time stamp for when a Space is scheduled to begin.

  # uncomment below to test the property
  # expect_equal(model.instance$`scheduled_start`, "EXPECTED_RESULT")
})

test_that("speaker_ids", {
  # tests for the property `speaker_ids` (array[character])
  # An array of user ids for people who were speakers in a Space.

  # uncomment below to test the property
  # expect_equal(model.instance$`speaker_ids`, "EXPECTED_RESULT")
})

test_that("started_at", {
  # tests for the property `started_at` (character)
  # When the Space was started as a date string.

  # uncomment below to test the property
  # expect_equal(model.instance$`started_at`, "EXPECTED_RESULT")
})

test_that("state", {
  # tests for the property `state` (character)
  # The current state of the Space.

  # uncomment below to test the property
  # expect_equal(model.instance$`state`, "EXPECTED_RESULT")
})

test_that("subscriber_count", {
  # tests for the property `subscriber_count` (integer)
  # The number of people who have either purchased a ticket or set a reminder for this Space.

  # uncomment below to test the property
  # expect_equal(model.instance$`subscriber_count`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)
  # The title of the Space.

  # uncomment below to test the property
  # expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("topics", {
  # tests for the property `topics` (array[SpaceTopicsInner])
  # The topics of a Space, as selected by its creator.

  # uncomment below to test the property
  # expect_equal(model.instance$`topics`, "EXPECTED_RESULT")
})

test_that("updated_at", {
  # tests for the property `updated_at` (character)
  # When the Space was last updated.

  # uncomment below to test the property
  # expect_equal(model.instance$`updated_at`, "EXPECTED_RESULT")
})
