# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UsersRetweetsCreateResponseData")

model_instance <- UsersRetweetsCreateResponseData$new()

test_that("retweeted", {
  # tests for the property `retweeted` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`retweeted`, "EXPECTED_RESULT")
})
