# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AnimatedGif")

model_instance <- AnimatedGif$new()

test_that("height", {
  # tests for the property `height` (integer)
  # The height of the media in pixels.

  # uncomment below to test the property
  # expect_equal(model.instance$`height`, "EXPECTED_RESULT")
})

test_that("media_key", {
  # tests for the property `media_key` (character)
  # The Media Key identifier for this attachment.

  # uncomment below to test the property
  # expect_equal(model.instance$`media_key`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  # expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("width", {
  # tests for the property `width` (integer)
  # The width of the media in pixels.

  # uncomment below to test the property
  # expect_equal(model.instance$`width`, "EXPECTED_RESULT")
})

test_that("preview_image_url", {
  # tests for the property `preview_image_url` (character)

  # uncomment below to test the property
  # expect_equal(model.instance$`preview_image_url`, "EXPECTED_RESULT")
})

test_that("variants", {
  # tests for the property `variants` (array[Variant])
  # An array of all available variants of the media.

  # uncomment below to test the property
  # expect_equal(model.instance$`variants`, "EXPECTED_RESULT")
})
