# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MentionFields")

model_instance <- MentionFields$new()

test_that("id", {
  # tests for the property `id` (character)
  # Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("username", {
  # tests for the property `username` (character)
  # The Twitter handle (screen name) of this user.

  # uncomment below to test the property
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})
