# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TweetComplianceStreamResponseOneOf1")

model_instance <- TweetComplianceStreamResponseOneOf1$new()

test_that("errors", {
  # tests for the property `errors` (array[Problem])

  # uncomment below to test the property
  # expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})
