# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserSuspendComplianceSchema")

model_instance <- UserSuspendComplianceSchema$new()

test_that("user_suspend", {
  # tests for the property `user_suspend` (UserComplianceSchema)

  # uncomment below to test the property
  # expect_equal(model.instance$`user_suspend`, "EXPECTED_RESULT")
})
