# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CashtagEntity")

model_instance <- CashtagEntity$new()

test_that("end", {
  # tests for the property `end` (integer)
  # Index (zero-based) at which position this entity ends.  The index is exclusive.

  # uncomment below to test the property
  #expect_equal(model.instance$`end`, "EXPECTED_RESULT")
})

test_that("start", {
  # tests for the property `start` (integer)
  # Index (zero-based) at which position this entity starts.  The index is inclusive.

  # uncomment below to test the property
  #expect_equal(model.instance$`start`, "EXPECTED_RESULT")
})

test_that("tag", {
  # tests for the property `tag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tag`, "EXPECTED_RESULT")
})
