# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ClientForbiddenProblemAllOf")

model_instance <- ClientForbiddenProblemAllOf$new()

test_that("reason", {
  # tests for the property `reason` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`reason`, "EXPECTED_RESULT")
})

test_that("registration_url", {
  # tests for the property `registration_url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`registration_url`, "EXPECTED_RESULT")
})
