# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserDeleteComplianceSchema")

model_instance <- UserDeleteComplianceSchema$new()

test_that("user_delete", {
  # tests for the property `user_delete` (UserComplianceSchema)

  # uncomment below to test the property
  # expect_equal(model.instance$`user_delete`, "EXPECTED_RESULT")
})
