# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TweetAttachments")

model_instance <- TweetAttachments$new()

test_that("media_keys", {
  # tests for the property `media_keys` (array[character])
  # A list of Media Keys for each one of the media attachments (if media are attached).

  # uncomment below to test the property
  #expect_equal(model.instance$`media_keys`, "EXPECTED_RESULT")
})

test_that("poll_ids", {
  # tests for the property `poll_ids` (array[character])
  # A list of poll IDs (if polls are attached).

  # uncomment below to test the property
  #expect_equal(model.instance$`poll_ids`, "EXPECTED_RESULT")
})
