# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TweetWithheldComplianceSchema")

model_instance <- TweetWithheldComplianceSchema$new()

test_that("withheld", {
  # tests for the property `withheld` (TweetTakedownComplianceSchema)

  # uncomment below to test the property
  #expect_equal(model.instance$`withheld`, "EXPECTED_RESULT")
})
