# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Get2TweetsIdQuoteTweetsResponseMeta")

model_instance <- Get2TweetsIdQuoteTweetsResponseMeta$new()

test_that("next_token", {
  # tests for the property `next_token` (character)
  # The next token.

  # uncomment below to test the property
  # expect_equal(model.instance$`next_token`, "EXPECTED_RESULT")
})

test_that("result_count", {
  # tests for the property `result_count` (integer)
  # The number of results returned in this response.

  # uncomment below to test the property
  # expect_equal(model.instance$`result_count`, "EXPECTED_RESULT")
})
