# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ListMutateResponseData")

model_instance <- ListMutateResponseData$new()

test_that("is_member", {
  # tests for the property `is_member` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_member`, "EXPECTED_RESULT")
})
