# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ListUpdateResponseData")

model_instance <- ListUpdateResponseData$new()

test_that("updated", {
  # tests for the property `updated` (character)

  # uncomment below to test the property
  # expect_equal(model.instance$`updated`, "EXPECTED_RESULT")
})
