# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserUndeleteComplianceSchema")

model_instance <- UserUndeleteComplianceSchema$new()

test_that("user_undelete", {
  # tests for the property `user_undelete` (UserComplianceSchema)

  # uncomment below to test the property
  #expect_equal(model.instance$`user_undelete`, "EXPECTED_RESULT")
})
