# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DuplicateRuleProblem")

model_instance <- DuplicateRuleProblem$new()

test_that("detail", {
  # tests for the property `detail` (character)

  # uncomment below to test the property
  # expect_equal(model.instance$`detail`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (integer)

  # uncomment below to test the property
  # expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)

  # uncomment below to test the property
  # expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  # expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property
  # expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  # expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})
