# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FilteredStreamingTweetResponse")

model_instance <- FilteredStreamingTweetResponse$new()

test_that("data", {
  # tests for the property `data` (Tweet)

  # uncomment below to test the property
  # expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

test_that("errors", {
  # tests for the property `errors` (array[Problem])

  # uncomment below to test the property
  # expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})

test_that("includes", {
  # tests for the property `includes` (Expansions)

  # uncomment below to test the property
  # expect_equal(model.instance$`includes`, "EXPECTED_RESULT")
})

test_that("matching_rules", {
  # tests for the property `matching_rules` (array[FilteredStreamingTweetResponseMatchingRulesInner])
  # The list of rules which matched the Tweet

  # uncomment below to test the property
  # expect_equal(model.instance$`matching_rules`, "EXPECTED_RESULT")
})
