# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TweetNonPublicMetrics")

model_instance <- TweetNonPublicMetrics$new()

test_that("impression_count", {
  # tests for the property `impression_count` (integer)
  # Number of times this Tweet has been viewed.

  # uncomment below to test the property
  #expect_equal(model.instance$`impression_count`, "EXPECTED_RESULT")
})
