# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UsersApi")

api_instance <- UsersApi$new()

test_that("find_my_user", {
  # tests for find_my_user
  # base path: https://api.twitter.com
  # User lookup me
  # This endpoint returns information about the requesting User.
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2UsersMeResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("find_user_by_id", {
  # tests for find_user_by_id
  # base path: https://api.twitter.com
  # User lookup by ID
  # This endpoint returns information about a User. Specify User by ID.
  # @param id character The ID of the User to lookup.
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2UsersIdResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("find_user_by_username", {
  # tests for find_user_by_username
  # base path: https://api.twitter.com
  # User lookup by username
  # This endpoint returns information about a User. Specify User by username.
  # @param username character A username.
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2UsersByUsernameUsernameResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("find_users_by_id", {
  # tests for find_users_by_id
  # base path: https://api.twitter.com
  # User lookup by IDs
  # This endpoint returns information about Users. Specify Users by their ID.
  # @param ids array[character] A list of User IDs, comma-separated. You can specify up to 100 IDs.
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2UsersResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("find_users_by_username", {
  # tests for find_users_by_username
  # base path: https://api.twitter.com
  # User lookup by usernames
  # This endpoint returns information about Users. Specify Users by their username.
  # @param usernames array[character] A list of usernames, comma-separated.
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2UsersByResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("list_get_followers", {
  # tests for list_get_followers
  # base path: https://api.twitter.com
  # Returns User objects that follow a List by the provided List ID
  # Returns a list of Users that follow a List by the provided List ID
  # @param id character The ID of the List.
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This parameter is used to get a specified 'page' of results. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2ListsIdFollowersResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("list_get_members", {
  # tests for list_get_members
  # base path: https://api.twitter.com
  # Returns User objects that are members of a List by the provided List ID.
  # Returns a list of Users that are members of a List by the provided List ID.
  # @param id character The ID of the List.
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This parameter is used to get a specified 'page' of results. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2ListsIdMembersResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("tweets_id_liking_users", {
  # tests for tweets_id_liking_users
  # base path: https://api.twitter.com
  # Returns User objects that have liked the provided Tweet ID
  # Returns a list of Users that have liked the provided Tweet ID
  # @param id character A single Tweet ID.
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This parameter is used to get the next 'page' of results. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2TweetsIdLikingUsersResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("tweets_id_retweeting_users", {
  # tests for tweets_id_retweeting_users
  # base path: https://api.twitter.com
  # Returns User objects that have retweeted the provided Tweet ID
  # Returns a list of Users that have retweeted the provided Tweet ID
  # @param id character A single Tweet ID.
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This parameter is used to get the next 'page' of results. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2TweetsIdRetweetedByResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_block", {
  # tests for users_id_block
  # base path: https://api.twitter.com
  # Block User by User ID
  # Causes the User (in the path) to block the target User. The User (in the path) must match the User context authorizing the request
  # @param id character The ID of the authenticated source User that is requesting to block the target User.
  # @param block_user_request BlockUserRequest 
  # @return [BlockUserMutationResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_blocking", {
  # tests for users_id_blocking
  # base path: https://api.twitter.com
  # Returns User objects that are blocked by provided User ID
  # Returns a list of Users that are blocked by the provided User ID
  # @param id character The ID of the authenticated source User for whom to return results.
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This parameter is used to get a specified 'page' of results. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2UsersIdBlockingResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_follow", {
  # tests for users_id_follow
  # base path: https://api.twitter.com
  # Follow User
  # Causes the User(in the path) to follow, or “request to follow” for protected Users, the target User. The User(in the path) must match the User context authorizing the request
  # @param id character The ID of the authenticated source User that is requesting to follow the target User.
  # @param users_following_create_request UsersFollowingCreateRequest  (optional)
  # @return [UsersFollowingCreateResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_followers", {
  # tests for users_id_followers
  # base path: https://api.twitter.com
  # Returns User objects that follow a List by the provided User ID
  # Returns a list of Users that follow the provided User ID
  # @param id character The ID of the User to lookup.
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This parameter is used to get a specified 'page' of results. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2UsersIdFollowersResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_following", {
  # tests for users_id_following
  # base path: https://api.twitter.com
  # Following by User ID
  # Returns a list of Users that are being followed by the provided User ID
  # @param id character The ID of the User to lookup.
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This parameter is used to get a specified 'page' of results. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2UsersIdFollowingResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_mute", {
  # tests for users_id_mute
  # base path: https://api.twitter.com
  # Mute User by User ID.
  # Causes the User (in the path) to mute the target User. The User (in the path) must match the User context authorizing the request.
  # @param id character The ID of the authenticated source User that is requesting to mute the target User.
  # @param mute_user_request MuteUserRequest  (optional)
  # @return [MuteUserMutationResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_muting", {
  # tests for users_id_muting
  # base path: https://api.twitter.com
  # Returns User objects that are muted by the provided User ID
  # Returns a list of Users that are muted by the provided User ID
  # @param id character The ID of the authenticated source User for whom to return results.
  # @param max_results integer The maximum number of results. (optional)
  # @param pagination_token character This parameter is used to get the next 'page' of results. (optional)
  # @param user_fields set[character] A comma separated list of User fields to display. (optional)
  # @param expansions set[character] A comma separated list of fields to expand. (optional)
  # @param tweet_fields set[character] A comma separated list of Tweet fields to display. (optional)
  # @return [Get2UsersIdMutingResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_unblock", {
  # tests for users_id_unblock
  # base path: https://api.twitter.com
  # Unblock User by User ID
  # Causes the source User to unblock the target User. The source User must match the User context authorizing the request
  # @param source_user_id character The ID of the authenticated source User that is requesting to unblock the target User.
  # @param target_user_id character The ID of the User that the source User is requesting to unblock.
  # @return [BlockUserMutationResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_unfollow", {
  # tests for users_id_unfollow
  # base path: https://api.twitter.com
  # Unfollow User
  # Causes the source User to unfollow the target User. The source User must match the User context authorizing the request
  # @param source_user_id character The ID of the authenticated source User that is requesting to unfollow the target User.
  # @param target_user_id character The ID of the User that the source User is requesting to unfollow.
  # @return [UsersFollowingDeleteResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("users_id_unmute", {
  # tests for users_id_unmute
  # base path: https://api.twitter.com
  # Unmute User by User ID
  # Causes the source User to unmute the target User. The source User must match the User context authorizing the request
  # @param source_user_id character The ID of the authenticated source User that is requesting to unmute the target User.
  # @param target_user_id character The ID of the User that the source User is requesting to unmute.
  # @return [MuteUserMutationResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
