# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ClientForbiddenProblem")

model_instance <- ClientForbiddenProblem$new()

test_that("detail", {
  # tests for the property `detail` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`detail`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("reason", {
  # tests for the property `reason` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`reason`, "EXPECTED_RESULT")
})

test_that("registration_url", {
  # tests for the property `registration_url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`registration_url`, "EXPECTED_RESULT")
})
