# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CashtagFields")

model_instance <- CashtagFields$new()

test_that("tag", {
  # tests for the property `tag` (character)

  # uncomment below to test the property
  # expect_equal(model.instance$`tag`, "EXPECTED_RESULT")
})
