#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title BlockUserMutationResponseData
#' @description BlockUserMutationResponseData Class
#' @format An \code{R6Class} generator object
#' @field blocking  character [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BlockUserMutationResponseData <- R6::R6Class(
  "BlockUserMutationResponseData",
  public = list(
    `blocking` = NULL,
    #' Initialize a new BlockUserMutationResponseData class.
    #'
    #' @description
    #' Initialize a new BlockUserMutationResponseData class.
    #'
    #' @param blocking blocking
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `blocking` = NULL, ...
    ) {
      if (!is.null(`blocking`)) {
        stopifnot(is.logical(`blocking`), length(`blocking`) == 1)
        self$`blocking` <- `blocking`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return BlockUserMutationResponseData in JSON format
    #' @export
    toJSON = function() {
      BlockUserMutationResponseDataObject <- list()
      if (!is.null(self$`blocking`)) {
        BlockUserMutationResponseDataObject[["blocking"]] <-
          self$`blocking`
      }

      BlockUserMutationResponseDataObject
    },
    #' Deserialize JSON string into an instance of BlockUserMutationResponseData
    #'
    #' @description
    #' Deserialize JSON string into an instance of BlockUserMutationResponseData
    #'
    #' @param input_json the JSON input
    #' @return the instance of BlockUserMutationResponseData
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`blocking`)) {
        self$`blocking` <- this_object$`blocking`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return BlockUserMutationResponseData in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`blocking`)) {
          sprintf(
          '"blocking":
            %s
                    ',
          tolower(self$`blocking`)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of BlockUserMutationResponseData
    #'
    #' @description
    #' Deserialize JSON string into an instance of BlockUserMutationResponseData
    #'
    #' @param input_json the JSON input
    #' @return the instance of BlockUserMutationResponseData
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`blocking` <- this_object$`blocking`
      self
    },
    #' Validate JSON input with respect to BlockUserMutationResponseData
    #'
    #' @description
    #' Validate JSON input with respect to BlockUserMutationResponseData and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of BlockUserMutationResponseData
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      invalid_fields
    }
  )
)

