#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title BookmarkMutationResponseData
#' @description BookmarkMutationResponseData Class
#' @format An \code{R6Class} generator object
#' @field bookmarked  character [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BookmarkMutationResponseData <- R6::R6Class(
  "BookmarkMutationResponseData",
  public = list(
    `bookmarked` = NULL,
    #' Initialize a new BookmarkMutationResponseData class.
    #'
    #' @description
    #' Initialize a new BookmarkMutationResponseData class.
    #'
    #' @param bookmarked bookmarked
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `bookmarked` = NULL, ...
    ) {
      if (!is.null(`bookmarked`)) {
        stopifnot(is.logical(`bookmarked`), length(`bookmarked`) == 1)
        self$`bookmarked` <- `bookmarked`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return BookmarkMutationResponseData in JSON format
    #' @export
    toJSON = function() {
      BookmarkMutationResponseDataObject <- list()
      if (!is.null(self$`bookmarked`)) {
        BookmarkMutationResponseDataObject[["bookmarked"]] <-
          self$`bookmarked`
      }

      BookmarkMutationResponseDataObject
    },
    #' Deserialize JSON string into an instance of BookmarkMutationResponseData
    #'
    #' @description
    #' Deserialize JSON string into an instance of BookmarkMutationResponseData
    #'
    #' @param input_json the JSON input
    #' @return the instance of BookmarkMutationResponseData
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`bookmarked`)) {
        self$`bookmarked` <- this_object$`bookmarked`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return BookmarkMutationResponseData in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`bookmarked`)) {
          sprintf(
          '"bookmarked":
            %s
                    ',
          tolower(self$`bookmarked`)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of BookmarkMutationResponseData
    #'
    #' @description
    #' Deserialize JSON string into an instance of BookmarkMutationResponseData
    #'
    #' @param input_json the JSON input
    #' @return the instance of BookmarkMutationResponseData
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`bookmarked` <- this_object$`bookmarked`
      self
    },
    #' Validate JSON input with respect to BookmarkMutationResponseData
    #'
    #' @description
    #' Validate JSON input with respect to BookmarkMutationResponseData and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of BookmarkMutationResponseData
    #' @export
    toString = function() {
      self$toJSONString()
    }
  )
)
