#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @export
ComplianceJobType <- R6::R6Class(
    "ComplianceJobType",
    public = list(
        initialize = function(...) {
            local.optional.var <- list(...)
            val <- unlist(local.optional.var)
            enumvec <- .parse_ComplianceJobType()

            stopifnot(length(val) == 1L)

            if (!val %in% enumvec)
                stop("Use one of the valid values: ",
                    paste0(enumvec, collapse = ", "))
            private$value <- val
        },
        toJSON = function() {
            jsonlite::toJSON(private$value, auto_unbox = TRUE)
        },
        fromJSON = function(ComplianceJobTypeJson) {
            private$value <- jsonlite::fromJSON(ComplianceJobTypeJson,
                simplifyVector = FALSE)
            self
        },
        toJSONString = function() {
            as.character(jsonlite::toJSON(private$value,
                auto_unbox = TRUE))
        },
        fromJSONString = function(ComplianceJobTypeJson) {
            private$value <- jsonlite::fromJSON(ComplianceJobTypeJson,
                simplifyVector = FALSE)
            self
        }
    ),
    private = list(
        value = NULL
    )
)

# add to utils.R
.parse_ComplianceJobType <- function(vals) {
    res <- gsub("^\\[|\\]$", "",
        "[tweets, users]"
    )
    unlist(strsplit(res, ", "))
}

