#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title CreateComplianceJobRequest
#' @description CreateComplianceJobRequest Class
#' @format An \code{R6Class} generator object
#' @field name  character [optional]
#' @field resumable  character [optional]
#' @field type  character
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CreateComplianceJobRequest <- R6::R6Class(
  "CreateComplianceJobRequest",
  public = list(
    `name` = NULL,
    `resumable` = NULL,
    `type` = NULL,
    #' Initialize a new CreateComplianceJobRequest class.
    #'
    #' @description
    #' Initialize a new CreateComplianceJobRequest class.
    #'
    #' @param type Type of compliance job to list.
    #' @param name User-provided name for a compliance job.
    #' @param resumable If true, this endpoint will return a pre-signed URL with resumable uploads enabled.
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `type`, `name` = NULL, `resumable` = NULL, ...
    ) {
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`resumable`)) {
        stopifnot(is.logical(`resumable`), length(`resumable`) == 1)
        self$`resumable` <- `resumable`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return CreateComplianceJobRequest in JSON format
    #' @export
    toJSON = function() {
      CreateComplianceJobRequestObject <- list()
      if (!is.null(self$`name`)) {
        CreateComplianceJobRequestObject[["name"]] <-
          self$`name`
      }
      if (!is.null(self$`resumable`)) {
        CreateComplianceJobRequestObject[["resumable"]] <-
          self$`resumable`
      }
      if (!is.null(self$`type`)) {
        CreateComplianceJobRequestObject[["type"]] <-
          self$`type`
      }

      CreateComplianceJobRequestObject
    },
    #' Deserialize JSON string into an instance of CreateComplianceJobRequest
    #'
    #' @description
    #' Deserialize JSON string into an instance of CreateComplianceJobRequest
    #'
    #' @param input_json the JSON input
    #' @return the instance of CreateComplianceJobRequest
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`name`)) {
        self$`name` <- this_object$`name`
      }
      if (!is.null(this_object$`resumable`)) {
        self$`resumable` <- this_object$`resumable`
      }
      if (!is.null(this_object$`type`)) {
        self$`type` <- this_object$`type`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return CreateComplianceJobRequest in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
          sprintf(
          '"name":
            "%s"
                    ',
          self$`name`
          )
        },
        if (!is.null(self$`resumable`)) {
          sprintf(
          '"resumable":
            %s
                    ',
          tolower(self$`resumable`)
          )
        },
        if (!is.null(self$`type`)) {
          sprintf(
          '"type":
            "%s"
                    ',
          self$`type`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of CreateComplianceJobRequest
    #'
    #' @description
    #' Deserialize JSON string into an instance of CreateComplianceJobRequest
    #'
    #' @param input_json the JSON input
    #' @return the instance of CreateComplianceJobRequest
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`name` <- this_object$`name`
      self$`resumable` <- this_object$`resumable`
      self$`type` <- this_object$`type`
      self
    },
    #' Validate JSON input with respect to CreateComplianceJobRequest
    #'
    #' @description
    #' Validate JSON input with respect to CreateComplianceJobRequest and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `type`
      if (!is.null(input_json$`type`)) {
        stopifnot(is.character(input_json$`type`), length(input_json$`type`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for CreateComplianceJobRequest: the required field `type` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of CreateComplianceJobRequest
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      if (nchar(self$`name`) > 64) {
        return(FALSE)
      }

      # check if the required `type` is null
      if (is.null(self$`type`)) {
        return(FALSE)
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      if (nchar(self$`name`) > 64) {
        invalid_fields["name"] = "Invalid length for `name`, must be smaller than or equal to 64."
      }

      # check if the required `type` is null
      if (is.null(self$`type`)) {
        invalid_fields["type"] = "Non-nullable required field `type` cannot be null."
      }

      invalid_fields
    }
  )
)

