#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title DeleteRulesRequest
#' @description DeleteRulesRequest Class
#' @format An \code{R6Class} generator object
#' @field delete  \link{DeleteRulesRequestDelete}
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DeleteRulesRequest <- R6::R6Class(
  "DeleteRulesRequest",
  public = list(
    `delete` = NULL,
    #' Initialize a new DeleteRulesRequest class.
    #'
    #' @description
    #' Initialize a new DeleteRulesRequest class.
    #'
    #' @param delete delete
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `delete`, ...
    ) {
      if (!missing(`delete`)) {
        stopifnot(R6::is.R6(`delete`))
        self$`delete` <- `delete`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return DeleteRulesRequest in JSON format
    #' @export
    toJSON = function() {
      DeleteRulesRequestObject <- list()
      if (!is.null(self$`delete`)) {
        DeleteRulesRequestObject[["delete"]] <-
          self$`delete`$toJSON()
      }

      DeleteRulesRequestObject
    },
    #' Deserialize JSON string into an instance of DeleteRulesRequest
    #'
    #' @description
    #' Deserialize JSON string into an instance of DeleteRulesRequest
    #'
    #' @param input_json the JSON input
    #' @return the instance of DeleteRulesRequest
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`delete`)) {
        delete_object <- DeleteRulesRequestDelete$new()
        delete_object$fromJSON(jsonlite::toJSON(this_object$delete, auto_unbox = TRUE, digits = NA))
        self$`delete` <- delete_object
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return DeleteRulesRequest in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`delete`)) {
          sprintf(
          '"delete":
          %s
          ',
          jsonlite::toJSON(self$`delete`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of DeleteRulesRequest
    #'
    #' @description
    #' Deserialize JSON string into an instance of DeleteRulesRequest
    #'
    #' @param input_json the JSON input
    #' @return the instance of DeleteRulesRequest
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`delete` <- DeleteRulesRequestDelete$new()$fromJSON(jsonlite::toJSON(this_object$delete, auto_unbox = TRUE, digits = NA))
      self
    },
    #' Validate JSON input with respect to DeleteRulesRequest
    #'
    #' @description
    #' Validate JSON input with respect to DeleteRulesRequest and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `delete`
      if (!is.null(input_json$`delete`)) {
        stopifnot(R6::is.R6(input_json$`delete`))
      } else {
        stop(paste("The JSON input `", input, "` is invalid for DeleteRulesRequest: the required field `delete` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of DeleteRulesRequest
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      # check if the required `delete` is null
      if (is.null(self$`delete`)) {
        FALSE
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      # check if the required `delete` is null
      if (is.null(self$`delete`)) {
        invalid_fields["delete"] <- "Non-nullable required field `delete` cannot be null."
      }

      invalid_fields
    }
  )
)
