#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title FilteredStreamingTweetResponseMatchingRulesInner
#' @description FilteredStreamingTweetResponseMatchingRulesInner Class
#' @format An \code{R6Class} generator object
#' @field id  character
#' @field tag  character [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FilteredStreamingTweetResponseMatchingRulesInner <- R6::R6Class(
  "FilteredStreamingTweetResponseMatchingRulesInner",
  public = list(
    `id` = NULL,
    `tag` = NULL,
    #' Initialize a new FilteredStreamingTweetResponseMatchingRulesInner class.
    #'
    #' @description
    #' Initialize a new FilteredStreamingTweetResponseMatchingRulesInner class.
    #'
    #' @param id Unique identifier of this rule.
    #' @param tag A tag meant for the labeling of user provided rules.
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `id`, `tag` = NULL, ...
    ) {
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`tag`)) {
        stopifnot(is.character(`tag`), length(`tag`) == 1)
        self$`tag` <- `tag`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return FilteredStreamingTweetResponseMatchingRulesInner in JSON format
    #' @export
    toJSON = function() {
      FilteredStreamingTweetResponseMatchingRulesInnerObject <- list()
      if (!is.null(self$`id`)) {
        FilteredStreamingTweetResponseMatchingRulesInnerObject[["id"]] <-
          self$`id`
      }
      if (!is.null(self$`tag`)) {
        FilteredStreamingTweetResponseMatchingRulesInnerObject[["tag"]] <-
          self$`tag`
      }

      FilteredStreamingTweetResponseMatchingRulesInnerObject
    },
    #' Deserialize JSON string into an instance of FilteredStreamingTweetResponseMatchingRulesInner
    #'
    #' @description
    #' Deserialize JSON string into an instance of FilteredStreamingTweetResponseMatchingRulesInner
    #'
    #' @param input_json the JSON input
    #' @return the instance of FilteredStreamingTweetResponseMatchingRulesInner
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`id`)) {
        self$`id` <- this_object$`id`
      }
      if (!is.null(this_object$`tag`)) {
        self$`tag` <- this_object$`tag`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return FilteredStreamingTweetResponseMatchingRulesInner in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
          sprintf(
          '"id":
            "%s"
                    ',
          self$`id`
          )
        },
        if (!is.null(self$`tag`)) {
          sprintf(
          '"tag":
            "%s"
                    ',
          self$`tag`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of FilteredStreamingTweetResponseMatchingRulesInner
    #'
    #' @description
    #' Deserialize JSON string into an instance of FilteredStreamingTweetResponseMatchingRulesInner
    #'
    #' @param input_json the JSON input
    #' @return the instance of FilteredStreamingTweetResponseMatchingRulesInner
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`id` <- this_object$`id`
      self$`tag` <- this_object$`tag`
      self
    },
    #' Validate JSON input with respect to FilteredStreamingTweetResponseMatchingRulesInner
    #'
    #' @description
    #' Validate JSON input with respect to FilteredStreamingTweetResponseMatchingRulesInner and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `id`
      if (!is.null(input_json$`id`)) {
        stopifnot(is.character(input_json$`id`), length(input_json$`id`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for FilteredStreamingTweetResponseMatchingRulesInner: the required field `id` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of FilteredStreamingTweetResponseMatchingRulesInner
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      # check if the required `id` is null
      if (is.null(self$`id`)) {
        return(FALSE)
      }

      if (!str_detect(self$`id`, "^[0-9]{1,19}$")) {
        return(FALSE)
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      # check if the required `id` is null
      if (is.null(self$`id`)) {
        invalid_fields["id"] = "Non-nullable required field `id` cannot be null."
      }

      if (!str_detect(self$`id`, "^[0-9]{1,19}$")) {
        invalid_fields["id"] = "Invalid value for `id`, must conform to the pattern ^[0-9]{1,19}$."
      }

      invalid_fields
    }
  )
)

