#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title FullTextEntitiesAnnotationsInnerAllOf
#' @description FullTextEntitiesAnnotationsInnerAllOf Class
#' @format An \code{R6Class} generator object
#' @field normalized_text  character [optional]
#' @field probability  numeric [optional]
#' @field type  character [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FullTextEntitiesAnnotationsInnerAllOf <- R6::R6Class(
  "FullTextEntitiesAnnotationsInnerAllOf",
  public = list(
    `normalized_text` = NULL,
    `probability` = NULL,
    `type` = NULL,
    #' Initialize a new FullTextEntitiesAnnotationsInnerAllOf class.
    #'
    #' @description
    #' Initialize a new FullTextEntitiesAnnotationsInnerAllOf class.
    #'
    #' @param normalized_text Text used to determine annotation.
    #' @param probability Confidence factor for annotation type.
    #' @param type Annotation type.
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `normalized_text` = NULL, `probability` = NULL, `type` = NULL, ...
    ) {
      if (!is.null(`normalized_text`)) {
        stopifnot(is.character(`normalized_text`), length(`normalized_text`) == 1)
        self$`normalized_text` <- `normalized_text`
      }
      if (!is.null(`probability`)) {
        stopifnot(is.numeric(`probability`), length(`probability`) == 1)
        self$`probability` <- `probability`
      }
      if (!is.null(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return FullTextEntitiesAnnotationsInnerAllOf in JSON format
    #' @export
    toJSON = function() {
      FullTextEntitiesAnnotationsInnerAllOfObject <- list()
      if (!is.null(self$`normalized_text`)) {
        FullTextEntitiesAnnotationsInnerAllOfObject[["normalized_text"]] <-
          self$`normalized_text`
      }
      if (!is.null(self$`probability`)) {
        FullTextEntitiesAnnotationsInnerAllOfObject[["probability"]] <-
          self$`probability`
      }
      if (!is.null(self$`type`)) {
        FullTextEntitiesAnnotationsInnerAllOfObject[["type"]] <-
          self$`type`
      }

      FullTextEntitiesAnnotationsInnerAllOfObject
    },
    #' Deserialize JSON string into an instance of FullTextEntitiesAnnotationsInnerAllOf
    #'
    #' @description
    #' Deserialize JSON string into an instance of FullTextEntitiesAnnotationsInnerAllOf
    #'
    #' @param input_json the JSON input
    #' @return the instance of FullTextEntitiesAnnotationsInnerAllOf
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`normalized_text`)) {
        self$`normalized_text` <- this_object$`normalized_text`
      }
      if (!is.null(this_object$`probability`)) {
        self$`probability` <- this_object$`probability`
      }
      if (!is.null(this_object$`type`)) {
        self$`type` <- this_object$`type`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return FullTextEntitiesAnnotationsInnerAllOf in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`normalized_text`)) {
          sprintf(
          '"normalized_text":
            "%s"
                    ',
          self$`normalized_text`
          )
        },
        if (!is.null(self$`probability`)) {
          sprintf(
          '"probability":
            %d
                    ',
          self$`probability`
          )
        },
        if (!is.null(self$`type`)) {
          sprintf(
          '"type":
            "%s"
                    ',
          self$`type`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of FullTextEntitiesAnnotationsInnerAllOf
    #'
    #' @description
    #' Deserialize JSON string into an instance of FullTextEntitiesAnnotationsInnerAllOf
    #'
    #' @param input_json the JSON input
    #' @return the instance of FullTextEntitiesAnnotationsInnerAllOf
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`normalized_text` <- this_object$`normalized_text`
      self$`probability` <- this_object$`probability`
      self$`type` <- this_object$`type`
      self
    },
    #' Validate JSON input with respect to FullTextEntitiesAnnotationsInnerAllOf
    #'
    #' @description
    #' Validate JSON input with respect to FullTextEntitiesAnnotationsInnerAllOf and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of FullTextEntitiesAnnotationsInnerAllOf
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      if (self$`probability` > 1) {
        return(FALSE)
      }
      if (self$`probability` < 0) {
        return(FALSE)
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      if (self$`probability` > 1) {
        invalid_fields["probability"] <- "Invalid value for `probability`, must be smaller than or equal to 1."
      }
      if (self$`probability` < 0) {
        invalid_fields["probability"] <- "Invalid value for `probability`, must be bigger than or equal to 0."
      }

      invalid_fields
    }
  )
)

