#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title Get2TweetsSearchAllResponse
#' @description Get2TweetsSearchAllResponse Class
#' @format An \code{R6Class} generator object
#' @field data  list( \link{Tweet} ) [optional]
#' @field errors  list( \link{Problem} ) [optional]
#' @field includes  \link{Expansions} [optional]
#' @field meta  \link{Get2TweetsSearchAllResponseMeta} [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Get2TweetsSearchAllResponse <- R6::R6Class(
  "Get2TweetsSearchAllResponse",
  public = list(
    `data` = NULL,
    `errors` = NULL,
    `includes` = NULL,
    `meta` = NULL,
    #' Initialize a new Get2TweetsSearchAllResponse class.
    #'
    #' @description
    #' Initialize a new Get2TweetsSearchAllResponse class.
    #'
    #' @param data data
    #' @param errors errors
    #' @param includes includes
    #' @param meta meta
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `data` = NULL, `errors` = NULL, `includes` = NULL, `meta` = NULL, ...
    ) {
      if (!is.null(`data`)) {
        stopifnot(is.vector(`data`), length(`data`) != 0)
        sapply(`data`, function(x) stopifnot(R6::is.R6(x)))
        self$`data` <- `data`
      }
      if (!is.null(`errors`)) {
        stopifnot(is.vector(`errors`), length(`errors`) != 0)
        sapply(`errors`, function(x) stopifnot(R6::is.R6(x)))
        self$`errors` <- `errors`
      }
      if (!is.null(`includes`)) {
        stopifnot(R6::is.R6(`includes`))
        self$`includes` <- `includes`
      }
      if (!is.null(`meta`)) {
        stopifnot(R6::is.R6(`meta`))
        self$`meta` <- `meta`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return Get2TweetsSearchAllResponse in JSON format
    #' @export
    toJSON = function() {
      Get2TweetsSearchAllResponseObject <- list()
      if (!is.null(self$`data`)) {
        Get2TweetsSearchAllResponseObject[["data"]] <-
          lapply(self$`data`, function(x) x$toJSON())
      }
      if (!is.null(self$`errors`)) {
        Get2TweetsSearchAllResponseObject[["errors"]] <-
          lapply(self$`errors`, function(x) x$toJSON())
      }
      if (!is.null(self$`includes`)) {
        Get2TweetsSearchAllResponseObject[["includes"]] <-
          self$`includes`$toJSON()
      }
      if (!is.null(self$`meta`)) {
        Get2TweetsSearchAllResponseObject[["meta"]] <-
          self$`meta`$toJSON()
      }

      Get2TweetsSearchAllResponseObject
    },
    #' Deserialize JSON string into an instance of Get2TweetsSearchAllResponse
    #'
    #' @description
    #' Deserialize JSON string into an instance of Get2TweetsSearchAllResponse
    #'
    #' @param input_json the JSON input
    #' @return the instance of Get2TweetsSearchAllResponse
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`data`)) {
        self$`data` <- ApiClient$new()$deserializeObj(this_object$`data`, "array[Tweet]", loadNamespace("twitter"))
      }
      if (!is.null(this_object$`errors`)) {
        self$`errors` <- ApiClient$new()$deserializeObj(this_object$`errors`, "array[Problem]", loadNamespace("twitter"))
      }
      if (!is.null(this_object$`includes`)) {
        includes_object <- Expansions$new()
        includes_object$fromJSON(jsonlite::toJSON(this_object$includes, auto_unbox = TRUE, digits = NA))
        self$`includes` <- includes_object
      }
      if (!is.null(this_object$`meta`)) {
        meta_object <- Get2TweetsSearchAllResponseMeta$new()
        meta_object$fromJSON(jsonlite::toJSON(this_object$meta, auto_unbox = TRUE, digits = NA))
        self$`meta` <- meta_object
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return Get2TweetsSearchAllResponse in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`data`)) {
          sprintf(
          '"data":
          [%s]
',
          paste(sapply(self$`data`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`errors`)) {
          sprintf(
          '"errors":
          [%s]
',
          paste(sapply(self$`errors`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`includes`)) {
          sprintf(
          '"includes":
          %s
          ',
          jsonlite::toJSON(self$`includes`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        },
        if (!is.null(self$`meta`)) {
          sprintf(
          '"meta":
          %s
          ',
          jsonlite::toJSON(self$`meta`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of Get2TweetsSearchAllResponse
    #'
    #' @description
    #' Deserialize JSON string into an instance of Get2TweetsSearchAllResponse
    #'
    #' @param input_json the JSON input
    #' @return the instance of Get2TweetsSearchAllResponse
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`data` <- ApiClient$new()$deserializeObj(this_object$`data`, "array[Tweet]", loadNamespace("twitter"))
      self$`errors` <- ApiClient$new()$deserializeObj(this_object$`errors`, "array[Problem]", loadNamespace("twitter"))
      self$`includes` <- Expansions$new()$fromJSON(jsonlite::toJSON(this_object$includes, auto_unbox = TRUE, digits = NA))
      self$`meta` <- Get2TweetsSearchAllResponseMeta$new()$fromJSON(jsonlite::toJSON(this_object$meta, auto_unbox = TRUE, digits = NA))
      self
    },
    #' Validate JSON input with respect to Get2TweetsSearchAllResponse
    #'
    #' @description
    #' Validate JSON input with respect to Get2TweetsSearchAllResponse and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of Get2TweetsSearchAllResponse
    #' @export
    toString = function() {
      self$toJSONString()
    }
  )
)
