#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title Get2TweetsCountsAllResponseMeta
#' @description Get2TweetsCountsAllResponseMeta Class
#' @format An \code{R6Class} generator object
#' @field newest_id  character [optional]
#' @field next_token  character [optional]
#' @field oldest_id  character [optional]
#' @field total_tweet_count  integer [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Get2TweetsCountsAllResponseMeta <- R6::R6Class(
  "Get2TweetsCountsAllResponseMeta",
  public = list(
    `newest_id` = NULL,
    `next_token` = NULL,
    `oldest_id` = NULL,
    `total_tweet_count` = NULL,
    #' Initialize a new Get2TweetsCountsAllResponseMeta class.
    #'
    #' @description
    #' Initialize a new Get2TweetsCountsAllResponseMeta class.
    #'
    #' @param newest_id The newest id in this response.
    #' @param next_token The next token.
    #' @param oldest_id The oldest id in this response.
    #' @param total_tweet_count The sum of results returned in this response.
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `newest_id` = NULL, `next_token` = NULL, `oldest_id` = NULL, `total_tweet_count` = NULL, ...
    ) {
      if (!is.null(`newest_id`)) {
        stopifnot(is.character(`newest_id`), length(`newest_id`) == 1)
        self$`newest_id` <- `newest_id`
      }
      if (!is.null(`next_token`)) {
        stopifnot(is.character(`next_token`), length(`next_token`) == 1)
        self$`next_token` <- `next_token`
      }
      if (!is.null(`oldest_id`)) {
        stopifnot(is.character(`oldest_id`), length(`oldest_id`) == 1)
        self$`oldest_id` <- `oldest_id`
      }
      if (!is.null(`total_tweet_count`)) {
        stopifnot(is.numeric(`total_tweet_count`), length(`total_tweet_count`) == 1)
        self$`total_tweet_count` <- `total_tweet_count`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return Get2TweetsCountsAllResponseMeta in JSON format
    #' @export
    toJSON = function() {
      Get2TweetsCountsAllResponseMetaObject <- list()
      if (!is.null(self$`newest_id`)) {
        Get2TweetsCountsAllResponseMetaObject[["newest_id"]] <-
          self$`newest_id`
      }
      if (!is.null(self$`next_token`)) {
        Get2TweetsCountsAllResponseMetaObject[["next_token"]] <-
          self$`next_token`
      }
      if (!is.null(self$`oldest_id`)) {
        Get2TweetsCountsAllResponseMetaObject[["oldest_id"]] <-
          self$`oldest_id`
      }
      if (!is.null(self$`total_tweet_count`)) {
        Get2TweetsCountsAllResponseMetaObject[["total_tweet_count"]] <-
          self$`total_tweet_count`
      }

      Get2TweetsCountsAllResponseMetaObject
    },
    #' Deserialize JSON string into an instance of Get2TweetsCountsAllResponseMeta
    #'
    #' @description
    #' Deserialize JSON string into an instance of Get2TweetsCountsAllResponseMeta
    #'
    #' @param input_json the JSON input
    #' @return the instance of Get2TweetsCountsAllResponseMeta
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`newest_id`)) {
        self$`newest_id` <- this_object$`newest_id`
      }
      if (!is.null(this_object$`next_token`)) {
        self$`next_token` <- this_object$`next_token`
      }
      if (!is.null(this_object$`oldest_id`)) {
        self$`oldest_id` <- this_object$`oldest_id`
      }
      if (!is.null(this_object$`total_tweet_count`)) {
        self$`total_tweet_count` <- this_object$`total_tweet_count`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return Get2TweetsCountsAllResponseMeta in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`newest_id`)) {
          sprintf(
          '"newest_id":
            "%s"
                    ',
          self$`newest_id`
          )
        },
        if (!is.null(self$`next_token`)) {
          sprintf(
          '"next_token":
            "%s"
                    ',
          self$`next_token`
          )
        },
        if (!is.null(self$`oldest_id`)) {
          sprintf(
          '"oldest_id":
            "%s"
                    ',
          self$`oldest_id`
          )
        },
        if (!is.null(self$`total_tweet_count`)) {
          sprintf(
          '"total_tweet_count":
            %d
                    ',
          self$`total_tweet_count`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of Get2TweetsCountsAllResponseMeta
    #'
    #' @description
    #' Deserialize JSON string into an instance of Get2TweetsCountsAllResponseMeta
    #'
    #' @param input_json the JSON input
    #' @return the instance of Get2TweetsCountsAllResponseMeta
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`newest_id` <- this_object$`newest_id`
      self$`next_token` <- this_object$`next_token`
      self$`oldest_id` <- this_object$`oldest_id`
      self$`total_tweet_count` <- this_object$`total_tweet_count`
      self
    },
    #' Validate JSON input with respect to Get2TweetsCountsAllResponseMeta
    #'
    #' @description
    #' Validate JSON input with respect to Get2TweetsCountsAllResponseMeta and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of Get2TweetsCountsAllResponseMeta
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      if (nchar(`next_token`) < 1) {
        FALSE
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      if (nchar(`next_token`) < 1) {
        invalid_fields[`next_token`] = "Invalid length for `next_token`, must be bigger than or equal to 1."
      }

      invalid_fields
    }
  )
)
