#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title HashtagEntity
#' @description HashtagEntity Class
#' @format An \code{R6Class} generator object
#' @field end  integer
#' @field start  integer
#' @field tag  character
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HashtagEntity <- R6::R6Class(
  "HashtagEntity",
  public = list(
    `end` = NULL,
    `start` = NULL,
    `tag` = NULL,
    #' Initialize a new HashtagEntity class.
    #'
    #' @description
    #' Initialize a new HashtagEntity class.
    #'
    #' @param end Index (zero-based) at which position this entity ends.  The index is exclusive.
    #' @param start Index (zero-based) at which position this entity starts.  The index is inclusive.
    #' @param tag The text of the Hashtag.
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `end`, `start`, `tag`, ...
    ) {
      if (!missing(`end`)) {
        stopifnot(is.numeric(`end`), length(`end`) == 1)
        self$`end` <- `end`
      }
      if (!missing(`start`)) {
        stopifnot(is.numeric(`start`), length(`start`) == 1)
        self$`start` <- `start`
      }
      if (!missing(`tag`)) {
        stopifnot(is.character(`tag`), length(`tag`) == 1)
        self$`tag` <- `tag`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return HashtagEntity in JSON format
    #' @export
    toJSON = function() {
      HashtagEntityObject <- list()
      if (!is.null(self$`end`)) {
        HashtagEntityObject[["end"]] <-
          self$`end`
      }
      if (!is.null(self$`start`)) {
        HashtagEntityObject[["start"]] <-
          self$`start`
      }
      if (!is.null(self$`tag`)) {
        HashtagEntityObject[["tag"]] <-
          self$`tag`
      }

      HashtagEntityObject
    },
    #' Deserialize JSON string into an instance of HashtagEntity
    #'
    #' @description
    #' Deserialize JSON string into an instance of HashtagEntity
    #'
    #' @param input_json the JSON input
    #' @return the instance of HashtagEntity
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`end`)) {
        self$`end` <- this_object$`end`
      }
      if (!is.null(this_object$`start`)) {
        self$`start` <- this_object$`start`
      }
      if (!is.null(this_object$`tag`)) {
        self$`tag` <- this_object$`tag`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return HashtagEntity in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`end`)) {
          sprintf(
          '"end":
            %d
                    ',
          self$`end`
          )
        },
        if (!is.null(self$`start`)) {
          sprintf(
          '"start":
            %d
                    ',
          self$`start`
          )
        },
        if (!is.null(self$`tag`)) {
          sprintf(
          '"tag":
            "%s"
                    ',
          self$`tag`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of HashtagEntity
    #'
    #' @description
    #' Deserialize JSON string into an instance of HashtagEntity
    #'
    #' @param input_json the JSON input
    #' @return the instance of HashtagEntity
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`end` <- this_object$`end`
      self$`start` <- this_object$`start`
      self$`tag` <- this_object$`tag`
      self
    },
    #' Validate JSON input with respect to HashtagEntity
    #'
    #' @description
    #' Validate JSON input with respect to HashtagEntity and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `end`
      if (!is.null(input_json$`end`)) {
        stopifnot(is.numeric(input_json$`end`), length(input_json$`end`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for HashtagEntity: the required field `end` is missing."))
      }
      # check the required field `start`
      if (!is.null(input_json$`start`)) {
        stopifnot(is.numeric(input_json$`start`), length(input_json$`start`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for HashtagEntity: the required field `start` is missing."))
      }
      # check the required field `tag`
      if (!is.null(input_json$`tag`)) {
        stopifnot(is.character(input_json$`tag`), length(input_json$`tag`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for HashtagEntity: the required field `tag` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of HashtagEntity
    #' @export
    toString = function() {
      self$toJSONString()
    }
  )
)
