#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title ListFollowedRequest
#' @description ListFollowedRequest Class
#' @format An \code{R6Class} generator object
#' @field list_id  character
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ListFollowedRequest <- R6::R6Class(
  "ListFollowedRequest",
  public = list(
    `list_id` = NULL,
    #' Initialize a new ListFollowedRequest class.
    #'
    #' @description
    #' Initialize a new ListFollowedRequest class.
    #'
    #' @param list_id The unique identifier of this List.
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `list_id`, ...
    ) {
      if (!missing(`list_id`)) {
        stopifnot(is.character(`list_id`), length(`list_id`) == 1)
        self$`list_id` <- `list_id`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return ListFollowedRequest in JSON format
    #' @export
    toJSON = function() {
      ListFollowedRequestObject <- list()
      if (!is.null(self$`list_id`)) {
        ListFollowedRequestObject[["list_id"]] <-
          self$`list_id`
      }

      ListFollowedRequestObject
    },
    #' Deserialize JSON string into an instance of ListFollowedRequest
    #'
    #' @description
    #' Deserialize JSON string into an instance of ListFollowedRequest
    #'
    #' @param input_json the JSON input
    #' @return the instance of ListFollowedRequest
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`list_id`)) {
        self$`list_id` <- this_object$`list_id`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return ListFollowedRequest in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`list_id`)) {
          sprintf(
          '"list_id":
            "%s"
                    ',
          self$`list_id`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of ListFollowedRequest
    #'
    #' @description
    #' Deserialize JSON string into an instance of ListFollowedRequest
    #'
    #' @param input_json the JSON input
    #' @return the instance of ListFollowedRequest
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`list_id` <- this_object$`list_id`
      self
    },
    #' Validate JSON input with respect to ListFollowedRequest
    #'
    #' @description
    #' Validate JSON input with respect to ListFollowedRequest and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `list_id`
      if (!is.null(input_json$`list_id`)) {
        stopifnot(is.character(input_json$`list_id`), length(input_json$`list_id`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for ListFollowedRequest: the required field `list_id` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of ListFollowedRequest
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      # check if the required `list_id` is null
      if (is.null(self$`list_id`)) {
        return(FALSE)
      }

      if (!str_detect(self$`list_id`, "^[0-9]{1,19}$")) {
        return(FALSE)
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      # check if the required `list_id` is null
      if (is.null(self$`list_id`)) {
        invalid_fields["list_id"] <- "Non-nullable required field `list_id` cannot be null."
      }

      if (!str_detect(self$`list_id`, "^[0-9]{1,19}$")) {
        invalid_fields["list_id"] <- "Invalid value for `list_id`, must conform to the pattern ^[0-9]{1,19}$."
      }

      invalid_fields
    }
  )
)

