#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title List
#' @description List Class
#' @format An \code{R6Class} generator object
#' @field created_at  character [optional]
#' @field description  character [optional]
#' @field follower_count  integer [optional]
#' @field id  character
#' @field member_count  integer [optional]
#' @field name  character
#' @field owner_id  character [optional]
#' @field item_private  character [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
List <- R6::R6Class(
  "List",
  public = list(
    `created_at` = NULL,
    `description` = NULL,
    `follower_count` = NULL,
    `id` = NULL,
    `member_count` = NULL,
    `name` = NULL,
    `owner_id` = NULL,
    `item_private` = NULL,
    #' Initialize a new List class.
    #'
    #' @description
    #' Initialize a new List class.
    #'
    #' @param id The unique identifier of this List.
    #' @param name The name of this List.
    #' @param created_at created_at
    #' @param description description
    #' @param follower_count follower_count
    #' @param member_count member_count
    #' @param owner_id Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
    #' @param item_private item_private
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `id`, `name`, `created_at` = NULL, `description` = NULL, `follower_count` = NULL, `member_count` = NULL, `owner_id` = NULL, `item_private` = NULL, ...
    ) {
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`created_at`)) {
        stopifnot(is.character(`created_at`), length(`created_at`) == 1)
        self$`created_at` <- `created_at`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`follower_count`)) {
        stopifnot(is.numeric(`follower_count`), length(`follower_count`) == 1)
        self$`follower_count` <- `follower_count`
      }
      if (!is.null(`member_count`)) {
        stopifnot(is.numeric(`member_count`), length(`member_count`) == 1)
        self$`member_count` <- `member_count`
      }
      if (!is.null(`owner_id`)) {
        stopifnot(is.character(`owner_id`), length(`owner_id`) == 1)
        self$`owner_id` <- `owner_id`
      }
      if (!is.null(`item_private`)) {
        stopifnot(is.logical(`item_private`), length(`item_private`) == 1)
        self$`item_private` <- `item_private`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return List in JSON format
    #' @export
    toJSON = function() {
      ListObject <- list()
      if (!is.null(self$`created_at`)) {
        ListObject[["created_at"]] <-
          self$`created_at`
      }
      if (!is.null(self$`description`)) {
        ListObject[["description"]] <-
          self$`description`
      }
      if (!is.null(self$`follower_count`)) {
        ListObject[["follower_count"]] <-
          self$`follower_count`
      }
      if (!is.null(self$`id`)) {
        ListObject[["id"]] <-
          self$`id`
      }
      if (!is.null(self$`member_count`)) {
        ListObject[["member_count"]] <-
          self$`member_count`
      }
      if (!is.null(self$`name`)) {
        ListObject[["name"]] <-
          self$`name`
      }
      if (!is.null(self$`owner_id`)) {
        ListObject[["owner_id"]] <-
          self$`owner_id`
      }
      if (!is.null(self$`item_private`)) {
        ListObject[["private"]] <-
          self$`item_private`
      }

      ListObject
    },
    #' Deserialize JSON string into an instance of List
    #'
    #' @description
    #' Deserialize JSON string into an instance of List
    #'
    #' @param input_json the JSON input
    #' @return the instance of List
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`created_at`)) {
        self$`created_at` <- this_object$`created_at`
      }
      if (!is.null(this_object$`description`)) {
        self$`description` <- this_object$`description`
      }
      if (!is.null(this_object$`follower_count`)) {
        self$`follower_count` <- this_object$`follower_count`
      }
      if (!is.null(this_object$`id`)) {
        self$`id` <- this_object$`id`
      }
      if (!is.null(this_object$`member_count`)) {
        self$`member_count` <- this_object$`member_count`
      }
      if (!is.null(this_object$`name`)) {
        self$`name` <- this_object$`name`
      }
      if (!is.null(this_object$`owner_id`)) {
        self$`owner_id` <- this_object$`owner_id`
      }
      if (!is.null(this_object$`private`)) {
        self$`item_private` <- this_object$`private`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return List in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`created_at`)) {
          sprintf(
          '"created_at":
            "%s"
                    ',
          self$`created_at`
          )
        },
        if (!is.null(self$`description`)) {
          sprintf(
          '"description":
            "%s"
                    ',
          self$`description`
          )
        },
        if (!is.null(self$`follower_count`)) {
          sprintf(
          '"follower_count":
            %d
                    ',
          self$`follower_count`
          )
        },
        if (!is.null(self$`id`)) {
          sprintf(
          '"id":
            "%s"
                    ',
          self$`id`
          )
        },
        if (!is.null(self$`member_count`)) {
          sprintf(
          '"member_count":
            %d
                    ',
          self$`member_count`
          )
        },
        if (!is.null(self$`name`)) {
          sprintf(
          '"name":
            "%s"
                    ',
          self$`name`
          )
        },
        if (!is.null(self$`owner_id`)) {
          sprintf(
          '"owner_id":
            "%s"
                    ',
          self$`owner_id`
          )
        },
        if (!is.null(self$`item_private`)) {
          sprintf(
          '"private":
            %s
                    ',
          tolower(self$`item_private`)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of List
    #'
    #' @description
    #' Deserialize JSON string into an instance of List
    #'
    #' @param input_json the JSON input
    #' @return the instance of List
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`created_at` <- this_object$`created_at`
      self$`description` <- this_object$`description`
      self$`follower_count` <- this_object$`follower_count`
      self$`id` <- this_object$`id`
      self$`member_count` <- this_object$`member_count`
      self$`name` <- this_object$`name`
      self$`owner_id` <- this_object$`owner_id`
      self$`item_private` <- this_object$`item_private`
      self
    },
    #' Validate JSON input with respect to List
    #'
    #' @description
    #' Validate JSON input with respect to List and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `id`
      if (!is.null(input_json$`id`)) {
        stopifnot(is.character(input_json$`id`), length(input_json$`id`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for List: the required field `id` is missing."))
      }
      # check the required field `name`
      if (!is.null(input_json$`name`)) {
        stopifnot(is.character(input_json$`name`), length(input_json$`name`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for List: the required field `name` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of List
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      # check if the required `id` is null
      if (is.null(self$`id`)) {
        return(FALSE)
      }

      if (!str_detect(self$`id`, "^[0-9]{1,19}$")) {
        return(FALSE)
      }

      # check if the required `name` is null
      if (is.null(self$`name`)) {
        return(FALSE)
      }

      if (!str_detect(self$`owner_id`, "^[0-9]{1,19}$")) {
        return(FALSE)
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      # check if the required `id` is null
      if (is.null(self$`id`)) {
        invalid_fields["id"] <- "Non-nullable required field `id` cannot be null."
      }

      if (!str_detect(self$`id`, "^[0-9]{1,19}$")) {
        invalid_fields["id"] <- "Invalid value for `id`, must conform to the pattern ^[0-9]{1,19}$."
      }

      # check if the required `name` is null
      if (is.null(self$`name`)) {
        invalid_fields["name"] <- "Non-nullable required field `name` cannot be null."
      }

      if (!str_detect(self$`owner_id`, "^[0-9]{1,19}$")) {
        invalid_fields["owner_id"] <- "Invalid value for `owner_id`, must conform to the pattern ^[0-9]{1,19}$."
      }

      invalid_fields
    }
  )
)

