#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title ListPinnedResponseData
#' @description ListPinnedResponseData Class
#' @format An \code{R6Class} generator object
#' @field pinned  character [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ListPinnedResponseData <- R6::R6Class(
  "ListPinnedResponseData",
  public = list(
    `pinned` = NULL,
    #' Initialize a new ListPinnedResponseData class.
    #'
    #' @description
    #' Initialize a new ListPinnedResponseData class.
    #'
    #' @param pinned pinned
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `pinned` = NULL, ...
    ) {
      if (!is.null(`pinned`)) {
        stopifnot(is.logical(`pinned`), length(`pinned`) == 1)
        self$`pinned` <- `pinned`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return ListPinnedResponseData in JSON format
    #' @export
    toJSON = function() {
      ListPinnedResponseDataObject <- list()
      if (!is.null(self$`pinned`)) {
        ListPinnedResponseDataObject[["pinned"]] <-
          self$`pinned`
      }

      ListPinnedResponseDataObject
    },
    #' Deserialize JSON string into an instance of ListPinnedResponseData
    #'
    #' @description
    #' Deserialize JSON string into an instance of ListPinnedResponseData
    #'
    #' @param input_json the JSON input
    #' @return the instance of ListPinnedResponseData
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`pinned`)) {
        self$`pinned` <- this_object$`pinned`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return ListPinnedResponseData in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`pinned`)) {
          sprintf(
          '"pinned":
            %s
                    ',
          tolower(self$`pinned`)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of ListPinnedResponseData
    #'
    #' @description
    #' Deserialize JSON string into an instance of ListPinnedResponseData
    #'
    #' @param input_json the JSON input
    #' @return the instance of ListPinnedResponseData
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`pinned` <- this_object$`pinned`
      self
    },
    #' Validate JSON input with respect to ListPinnedResponseData
    #'
    #' @description
    #' Validate JSON input with respect to ListPinnedResponseData and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of ListPinnedResponseData
    #' @export
    toString = function() {
      self$toJSONString()
    }
  )
)
