#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title MentionEntity
#' @description MentionEntity Class
#' @format An \code{R6Class} generator object
#' @field end  integer
#' @field start  integer
#' @field id  character [optional]
#' @field username  character
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MentionEntity <- R6::R6Class(
  "MentionEntity",
  public = list(
    `end` = NULL,
    `start` = NULL,
    `id` = NULL,
    `username` = NULL,
    #' Initialize a new MentionEntity class.
    #'
    #' @description
    #' Initialize a new MentionEntity class.
    #'
    #' @param end Index (zero-based) at which position this entity ends.  The index is exclusive.
    #' @param start Index (zero-based) at which position this entity starts.  The index is inclusive.
    #' @param username The Twitter handle (screen name) of this user.
    #' @param id Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `end`, `start`, `username`, `id` = NULL, ...
    ) {
      if (!missing(`end`)) {
        stopifnot(is.numeric(`end`), length(`end`) == 1)
        self$`end` <- `end`
      }
      if (!missing(`start`)) {
        stopifnot(is.numeric(`start`), length(`start`) == 1)
        self$`start` <- `start`
      }
      if (!missing(`username`)) {
        stopifnot(is.character(`username`), length(`username`) == 1)
        self$`username` <- `username`
      }
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return MentionEntity in JSON format
    #' @export
    toJSON = function() {
      MentionEntityObject <- list()
      if (!is.null(self$`end`)) {
        MentionEntityObject[["end"]] <-
          self$`end`
      }
      if (!is.null(self$`start`)) {
        MentionEntityObject[["start"]] <-
          self$`start`
      }
      if (!is.null(self$`id`)) {
        MentionEntityObject[["id"]] <-
          self$`id`
      }
      if (!is.null(self$`username`)) {
        MentionEntityObject[["username"]] <-
          self$`username`
      }

      MentionEntityObject
    },
    #' Deserialize JSON string into an instance of MentionEntity
    #'
    #' @description
    #' Deserialize JSON string into an instance of MentionEntity
    #'
    #' @param input_json the JSON input
    #' @return the instance of MentionEntity
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`end`)) {
        self$`end` <- this_object$`end`
      }
      if (!is.null(this_object$`start`)) {
        self$`start` <- this_object$`start`
      }
      if (!is.null(this_object$`id`)) {
        self$`id` <- this_object$`id`
      }
      if (!is.null(this_object$`username`)) {
        self$`username` <- this_object$`username`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return MentionEntity in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`end`)) {
          sprintf(
          '"end":
            %d
                    ',
          self$`end`
          )
        },
        if (!is.null(self$`start`)) {
          sprintf(
          '"start":
            %d
                    ',
          self$`start`
          )
        },
        if (!is.null(self$`id`)) {
          sprintf(
          '"id":
            "%s"
                    ',
          self$`id`
          )
        },
        if (!is.null(self$`username`)) {
          sprintf(
          '"username":
            "%s"
                    ',
          self$`username`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of MentionEntity
    #'
    #' @description
    #' Deserialize JSON string into an instance of MentionEntity
    #'
    #' @param input_json the JSON input
    #' @return the instance of MentionEntity
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`end` <- this_object$`end`
      self$`start` <- this_object$`start`
      self$`id` <- this_object$`id`
      self$`username` <- this_object$`username`
      self
    },
    #' Validate JSON input with respect to MentionEntity
    #'
    #' @description
    #' Validate JSON input with respect to MentionEntity and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `end`
      if (!is.null(input_json$`end`)) {
        stopifnot(is.numeric(input_json$`end`), length(input_json$`end`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for MentionEntity: the required field `end` is missing."))
      }
      # check the required field `start`
      if (!is.null(input_json$`start`)) {
        stopifnot(is.numeric(input_json$`start`), length(input_json$`start`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for MentionEntity: the required field `start` is missing."))
      }
      # check the required field `username`
      if (!is.null(input_json$`username`)) {
        stopifnot(is.character(input_json$`username`), length(input_json$`username`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for MentionEntity: the required field `username` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of MentionEntity
    #' @export
    toString = function() {
      self$toJSONString()
    }
  )
)
