#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title OperationalDisconnectProblem
#' @description OperationalDisconnectProblem Class
#' @format An \code{R6Class} generator object
#' @field detail  character [optional]
#' @field status  integer [optional]
#' @field title  character
#' @field type  character
#' @field disconnect_type  character [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OperationalDisconnectProblem <- R6::R6Class(
  "OperationalDisconnectProblem",
  inherit = Problem,
  public = list(
    `detail` = NULL,
    `status` = NULL,
    `title` = NULL,
    `type` = NULL,
    `disconnect_type` = NULL,
    #' Initialize a new OperationalDisconnectProblem class.
    #'
    #' @description
    #' Initialize a new OperationalDisconnectProblem class.
    #'
    #' @param title title
    #' @param type type
    #' @param detail detail
    #' @param status status
    #' @param disconnect_type disconnect_type
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `title`, `type`, `detail` = NULL, `status` = NULL, `disconnect_type` = NULL, ...
    ) {
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!is.null(`detail`)) {
        stopifnot(is.character(`detail`), length(`detail`) == 1)
        self$`detail` <- `detail`
      }
      if (!is.null(`status`)) {
        stopifnot(is.numeric(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!is.null(`disconnect_type`)) {
        stopifnot(is.character(`disconnect_type`), length(`disconnect_type`) == 1)
        self$`disconnect_type` <- `disconnect_type`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return OperationalDisconnectProblem in JSON format
    #' @export
    toJSON = function() {
      OperationalDisconnectProblemObject <- list()
      if (!is.null(self$`detail`)) {
        OperationalDisconnectProblemObject[["detail"]] <-
          self$`detail`
      }
      if (!is.null(self$`status`)) {
        OperationalDisconnectProblemObject[["status"]] <-
          self$`status`
      }
      if (!is.null(self$`title`)) {
        OperationalDisconnectProblemObject[["title"]] <-
          self$`title`
      }
      if (!is.null(self$`type`)) {
        OperationalDisconnectProblemObject[["type"]] <-
          self$`type`
      }
      if (!is.null(self$`disconnect_type`)) {
        OperationalDisconnectProblemObject[["disconnect_type"]] <-
          self$`disconnect_type`
      }

      OperationalDisconnectProblemObject
    },
    #' Deserialize JSON string into an instance of OperationalDisconnectProblem
    #'
    #' @description
    #' Deserialize JSON string into an instance of OperationalDisconnectProblem
    #'
    #' @param input_json the JSON input
    #' @return the instance of OperationalDisconnectProblem
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`detail`)) {
        self$`detail` <- this_object$`detail`
      }
      if (!is.null(this_object$`status`)) {
        self$`status` <- this_object$`status`
      }
      if (!is.null(this_object$`title`)) {
        self$`title` <- this_object$`title`
      }
      if (!is.null(this_object$`type`)) {
        self$`type` <- this_object$`type`
      }
      if (!is.null(this_object$`disconnect_type`)) {
        self$`disconnect_type` <- this_object$`disconnect_type`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return OperationalDisconnectProblem in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`detail`)) {
          sprintf(
          '"detail":
            "%s"
                    ',
          self$`detail`
          )
        },
        if (!is.null(self$`status`)) {
          sprintf(
          '"status":
            %d
                    ',
          self$`status`
          )
        },
        if (!is.null(self$`title`)) {
          sprintf(
          '"title":
            "%s"
                    ',
          self$`title`
          )
        },
        if (!is.null(self$`type`)) {
          sprintf(
          '"type":
            "%s"
                    ',
          self$`type`
          )
        },
        if (!is.null(self$`disconnect_type`)) {
          sprintf(
          '"disconnect_type":
            "%s"
                    ',
          self$`disconnect_type`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of OperationalDisconnectProblem
    #'
    #' @description
    #' Deserialize JSON string into an instance of OperationalDisconnectProblem
    #'
    #' @param input_json the JSON input
    #' @return the instance of OperationalDisconnectProblem
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`detail` <- this_object$`detail`
      self$`status` <- this_object$`status`
      self$`title` <- this_object$`title`
      self$`type` <- this_object$`type`
      self$`disconnect_type` <- this_object$`disconnect_type`
      self
    },
    #' Validate JSON input with respect to OperationalDisconnectProblem
    #'
    #' @description
    #' Validate JSON input with respect to OperationalDisconnectProblem and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `title`
      if (!is.null(input_json$`title`)) {
        stopifnot(is.character(input_json$`title`), length(input_json$`title`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for OperationalDisconnectProblem: the required field `title` is missing."))
      }
      # check the required field `type`
      if (!is.null(input_json$`type`)) {
        stopifnot(is.character(input_json$`type`), length(input_json$`type`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for OperationalDisconnectProblem: the required field `type` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of OperationalDisconnectProblem
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      # check if the required `title` is null
      if (is.null(self$`title`)) {
        return(FALSE)
      }

      # check if the required `type` is null
      if (is.null(self$`type`)) {
        return(FALSE)
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      # check if the required `title` is null
      if (is.null(self$`title`)) {
        invalid_fields["title"] = "Non-nullable required field `title` cannot be null."
      }

      # check if the required `type` is null
      if (is.null(self$`type`)) {
        invalid_fields["type"] = "Non-nullable required field `type` cannot be null."
      }

      invalid_fields
    }
  )
)

