#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title TweetHideResponseData
#' @description TweetHideResponseData Class
#' @format An \code{R6Class} generator object
#' @field hidden  character [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TweetHideResponseData <- R6::R6Class(
  "TweetHideResponseData",
  public = list(
    `hidden` = NULL,
    #' Initialize a new TweetHideResponseData class.
    #'
    #' @description
    #' Initialize a new TweetHideResponseData class.
    #'
    #' @param hidden hidden
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `hidden` = NULL, ...
    ) {
      if (!is.null(`hidden`)) {
        stopifnot(is.logical(`hidden`), length(`hidden`) == 1)
        self$`hidden` <- `hidden`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return TweetHideResponseData in JSON format
    #' @export
    toJSON = function() {
      TweetHideResponseDataObject <- list()
      if (!is.null(self$`hidden`)) {
        TweetHideResponseDataObject[["hidden"]] <-
          self$`hidden`
      }

      TweetHideResponseDataObject
    },
    #' Deserialize JSON string into an instance of TweetHideResponseData
    #'
    #' @description
    #' Deserialize JSON string into an instance of TweetHideResponseData
    #'
    #' @param input_json the JSON input
    #' @return the instance of TweetHideResponseData
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`hidden`)) {
        self$`hidden` <- this_object$`hidden`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return TweetHideResponseData in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`hidden`)) {
          sprintf(
          '"hidden":
            %s
                    ',
          tolower(self$`hidden`)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of TweetHideResponseData
    #'
    #' @description
    #' Deserialize JSON string into an instance of TweetHideResponseData
    #'
    #' @param input_json the JSON input
    #' @return the instance of TweetHideResponseData
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`hidden` <- this_object$`hidden`
      self
    },
    #' Validate JSON input with respect to TweetHideResponseData
    #'
    #' @description
    #' Validate JSON input with respect to TweetHideResponseData and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of TweetHideResponseData
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      invalid_fields
    }
  )
)
