#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title TweetUndropComplianceSchema
#' @description TweetUndropComplianceSchema Class
#' @format An \code{R6Class} generator object
#' @field undrop  \link{TweetComplianceSchema}
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TweetUndropComplianceSchema <- R6::R6Class(
  "TweetUndropComplianceSchema",
  public = list(
    `undrop` = NULL,
    #' Initialize a new TweetUndropComplianceSchema class.
    #'
    #' @description
    #' Initialize a new TweetUndropComplianceSchema class.
    #'
    #' @param undrop undrop
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `undrop`, ...
    ) {
      if (!missing(`undrop`)) {
        stopifnot(R6::is.R6(`undrop`))
        self$`undrop` <- `undrop`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return TweetUndropComplianceSchema in JSON format
    #' @export
    toJSON = function() {
      TweetUndropComplianceSchemaObject <- list()
      if (!is.null(self$`undrop`)) {
        TweetUndropComplianceSchemaObject[["undrop"]] <-
          self$`undrop`$toJSON()
      }

      TweetUndropComplianceSchemaObject
    },
    #' Deserialize JSON string into an instance of TweetUndropComplianceSchema
    #'
    #' @description
    #' Deserialize JSON string into an instance of TweetUndropComplianceSchema
    #'
    #' @param input_json the JSON input
    #' @return the instance of TweetUndropComplianceSchema
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`undrop`)) {
        undrop_object <- TweetComplianceSchema$new()
        undrop_object$fromJSON(jsonlite::toJSON(this_object$undrop, auto_unbox = TRUE, digits = NA))
        self$`undrop` <- undrop_object
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return TweetUndropComplianceSchema in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`undrop`)) {
          sprintf(
          '"undrop":
          %s
          ',
          jsonlite::toJSON(self$`undrop`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of TweetUndropComplianceSchema
    #'
    #' @description
    #' Deserialize JSON string into an instance of TweetUndropComplianceSchema
    #'
    #' @param input_json the JSON input
    #' @return the instance of TweetUndropComplianceSchema
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`undrop` <- TweetComplianceSchema$new()$fromJSON(jsonlite::toJSON(this_object$undrop, auto_unbox = TRUE, digits = NA))
      self
    },
    #' Validate JSON input with respect to TweetUndropComplianceSchema
    #'
    #' @description
    #' Validate JSON input with respect to TweetUndropComplianceSchema and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `undrop`
      if (!is.null(input_json$`undrop`)) {
        stopifnot(R6::is.R6(input_json$`undrop`))
      } else {
        stop(paste("The JSON input `", input, "` is invalid for TweetUndropComplianceSchema: the required field `undrop` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of TweetUndropComplianceSchema
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      # check if the required `undrop` is null
      if (is.null(self$`undrop`)) {
        return(FALSE)
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      # check if the required `undrop` is null
      if (is.null(self$`undrop`)) {
        invalid_fields["undrop"] <- "Non-nullable required field `undrop` cannot be null."
      }

      invalid_fields
    }
  )
)

