#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title TweetDeleteResponseData
#' @description TweetDeleteResponseData Class
#' @format An \code{R6Class} generator object
#' @field deleted  character
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TweetDeleteResponseData <- R6::R6Class(
  "TweetDeleteResponseData",
  public = list(
    `deleted` = NULL,
    #' Initialize a new TweetDeleteResponseData class.
    #'
    #' @description
    #' Initialize a new TweetDeleteResponseData class.
    #'
    #' @param deleted deleted
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `deleted`, ...
    ) {
      if (!missing(`deleted`)) {
        stopifnot(is.logical(`deleted`), length(`deleted`) == 1)
        self$`deleted` <- `deleted`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return TweetDeleteResponseData in JSON format
    #' @export
    toJSON = function() {
      TweetDeleteResponseDataObject <- list()
      if (!is.null(self$`deleted`)) {
        TweetDeleteResponseDataObject[["deleted"]] <-
          self$`deleted`
      }

      TweetDeleteResponseDataObject
    },
    #' Deserialize JSON string into an instance of TweetDeleteResponseData
    #'
    #' @description
    #' Deserialize JSON string into an instance of TweetDeleteResponseData
    #'
    #' @param input_json the JSON input
    #' @return the instance of TweetDeleteResponseData
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`deleted`)) {
        self$`deleted` <- this_object$`deleted`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return TweetDeleteResponseData in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`deleted`)) {
          sprintf(
          '"deleted":
            %s
                    ',
          tolower(self$`deleted`)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of TweetDeleteResponseData
    #'
    #' @description
    #' Deserialize JSON string into an instance of TweetDeleteResponseData
    #'
    #' @param input_json the JSON input
    #' @return the instance of TweetDeleteResponseData
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`deleted` <- this_object$`deleted`
      self
    },
    #' Validate JSON input with respect to TweetDeleteResponseData
    #'
    #' @description
    #' Validate JSON input with respect to TweetDeleteResponseData and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `deleted`
      if (!is.null(input_json$`deleted`)) {
        stopifnot(is.logical(input_json$`deleted`), length(input_json$`deleted`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for TweetDeleteResponseData: the required field `deleted` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of TweetDeleteResponseData
    #' @export
    toString = function() {
      self$toJSONString()
    }
  )
)
