#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title TweetTakedownComplianceSchema
#' @description TweetTakedownComplianceSchema Class
#' @format An \code{R6Class} generator object
#' @field event_at  character
#' @field quote_tweet_id  character [optional]
#' @field tweet  \link{TweetComplianceSchemaTweet}
#' @field withheld_in_countries  list( character )
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TweetTakedownComplianceSchema <- R6::R6Class(
  "TweetTakedownComplianceSchema",
  public = list(
    `event_at` = NULL,
    `quote_tweet_id` = NULL,
    `tweet` = NULL,
    `withheld_in_countries` = NULL,
    #' Initialize a new TweetTakedownComplianceSchema class.
    #'
    #' @description
    #' Initialize a new TweetTakedownComplianceSchema class.
    #'
    #' @param event_at Event time.
    #' @param tweet tweet
    #' @param withheld_in_countries withheld_in_countries
    #' @param quote_tweet_id Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `event_at`, `tweet`, `withheld_in_countries`, `quote_tweet_id` = NULL, ...
    ) {
      if (!missing(`event_at`)) {
        stopifnot(is.character(`event_at`), length(`event_at`) == 1)
        self$`event_at` <- `event_at`
      }
      if (!missing(`tweet`)) {
        stopifnot(R6::is.R6(`tweet`))
        self$`tweet` <- `tweet`
      }
      if (!missing(`withheld_in_countries`)) {
        stopifnot(is.vector(`withheld_in_countries`), length(`withheld_in_countries`) != 0)
        sapply(`withheld_in_countries`, function(x) stopifnot(is.character(x)))
        self$`withheld_in_countries` <- `withheld_in_countries`
      }
      if (!is.null(`quote_tweet_id`)) {
        stopifnot(is.character(`quote_tweet_id`), length(`quote_tweet_id`) == 1)
        self$`quote_tweet_id` <- `quote_tweet_id`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return TweetTakedownComplianceSchema in JSON format
    #' @export
    toJSON = function() {
      TweetTakedownComplianceSchemaObject <- list()
      if (!is.null(self$`event_at`)) {
        TweetTakedownComplianceSchemaObject[["event_at"]] <-
          self$`event_at`
      }
      if (!is.null(self$`quote_tweet_id`)) {
        TweetTakedownComplianceSchemaObject[["quote_tweet_id"]] <-
          self$`quote_tweet_id`
      }
      if (!is.null(self$`tweet`)) {
        TweetTakedownComplianceSchemaObject[["tweet"]] <-
          self$`tweet`$toJSON()
      }
      if (!is.null(self$`withheld_in_countries`)) {
        TweetTakedownComplianceSchemaObject[["withheld_in_countries"]] <-
          self$`withheld_in_countries`
      }

      TweetTakedownComplianceSchemaObject
    },
    #' Deserialize JSON string into an instance of TweetTakedownComplianceSchema
    #'
    #' @description
    #' Deserialize JSON string into an instance of TweetTakedownComplianceSchema
    #'
    #' @param input_json the JSON input
    #' @return the instance of TweetTakedownComplianceSchema
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`event_at`)) {
        self$`event_at` <- this_object$`event_at`
      }
      if (!is.null(this_object$`quote_tweet_id`)) {
        self$`quote_tweet_id` <- this_object$`quote_tweet_id`
      }
      if (!is.null(this_object$`tweet`)) {
        tweet_object <- TweetComplianceSchemaTweet$new()
        tweet_object$fromJSON(jsonlite::toJSON(this_object$tweet, auto_unbox = TRUE, digits = NA))
        self$`tweet` <- tweet_object
      }
      if (!is.null(this_object$`withheld_in_countries`)) {
        self$`withheld_in_countries` <- ApiClient$new()$deserializeObj(this_object$`withheld_in_countries`, "array[character]", loadNamespace("twitter"))
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return TweetTakedownComplianceSchema in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`event_at`)) {
          sprintf(
          '"event_at":
            "%s"
                    ',
          self$`event_at`
          )
        },
        if (!is.null(self$`quote_tweet_id`)) {
          sprintf(
          '"quote_tweet_id":
            "%s"
                    ',
          self$`quote_tweet_id`
          )
        },
        if (!is.null(self$`tweet`)) {
          sprintf(
          '"tweet":
          %s
          ',
          jsonlite::toJSON(self$`tweet`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        },
        if (!is.null(self$`withheld_in_countries`)) {
          sprintf(
          '"withheld_in_countries":
             [%s]
          ',
          paste(unlist(lapply(self$`withheld_in_countries`, function(x) paste0('"', x, '"'))), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of TweetTakedownComplianceSchema
    #'
    #' @description
    #' Deserialize JSON string into an instance of TweetTakedownComplianceSchema
    #'
    #' @param input_json the JSON input
    #' @return the instance of TweetTakedownComplianceSchema
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`event_at` <- this_object$`event_at`
      self$`quote_tweet_id` <- this_object$`quote_tweet_id`
      self$`tweet` <- TweetComplianceSchemaTweet$new()$fromJSON(jsonlite::toJSON(this_object$tweet, auto_unbox = TRUE, digits = NA))
      self$`withheld_in_countries` <- ApiClient$new()$deserializeObj(this_object$`withheld_in_countries`, "array[character]", loadNamespace("twitter"))
      self
    },
    #' Validate JSON input with respect to TweetTakedownComplianceSchema
    #'
    #' @description
    #' Validate JSON input with respect to TweetTakedownComplianceSchema and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `event_at`
      if (!is.null(input_json$`event_at`)) {
        stopifnot(is.character(input_json$`event_at`), length(input_json$`event_at`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for TweetTakedownComplianceSchema: the required field `event_at` is missing."))
      }
      # check the required field `tweet`
      if (!is.null(input_json$`tweet`)) {
        stopifnot(R6::is.R6(input_json$`tweet`))
      } else {
        stop(paste("The JSON input `", input, "` is invalid for TweetTakedownComplianceSchema: the required field `tweet` is missing."))
      }
      # check the required field `withheld_in_countries`
      if (!is.null(input_json$`withheld_in_countries`)) {
        stopifnot(is.vector(input_json$`withheld_in_countries`), length(input_json$`withheld_in_countries`) != 0)
        tmp <- sapply(input_json$`withheld_in_countries`, function(x) stopifnot(is.character(x)))
      } else {
        stop(paste("The JSON input `", input, "` is invalid for TweetTakedownComplianceSchema: the required field `withheld_in_countries` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of TweetTakedownComplianceSchema
    #' @export
    toString = function() {
      self$toJSONString()
    }
  )
)
