#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title TweetPromotedMetrics
#' @description TweetPromotedMetrics Class
#' @format An \code{R6Class} generator object
#' @field impression_count  integer [optional]
#' @field like_count  integer [optional]
#' @field reply_count  integer [optional]
#' @field retweet_count  integer [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TweetPromotedMetrics <- R6::R6Class(
  "TweetPromotedMetrics",
  public = list(
    `impression_count` = NULL,
    `like_count` = NULL,
    `reply_count` = NULL,
    `retweet_count` = NULL,
    #' Initialize a new TweetPromotedMetrics class.
    #'
    #' @description
    #' Initialize a new TweetPromotedMetrics class.
    #'
    #' @param impression_count Number of times this Tweet has been viewed.
    #' @param like_count Number of times this Tweet has been liked.
    #' @param reply_count Number of times this Tweet has been replied to.
    #' @param retweet_count Number of times this Tweet has been Retweeted.
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `impression_count` = NULL, `like_count` = NULL, `reply_count` = NULL, `retweet_count` = NULL, ...
    ) {
      if (!is.null(`impression_count`)) {
        stopifnot(is.numeric(`impression_count`), length(`impression_count`) == 1)
        self$`impression_count` <- `impression_count`
      }
      if (!is.null(`like_count`)) {
        stopifnot(is.numeric(`like_count`), length(`like_count`) == 1)
        self$`like_count` <- `like_count`
      }
      if (!is.null(`reply_count`)) {
        stopifnot(is.numeric(`reply_count`), length(`reply_count`) == 1)
        self$`reply_count` <- `reply_count`
      }
      if (!is.null(`retweet_count`)) {
        stopifnot(is.numeric(`retweet_count`), length(`retweet_count`) == 1)
        self$`retweet_count` <- `retweet_count`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return TweetPromotedMetrics in JSON format
    #' @export
    toJSON = function() {
      TweetPromotedMetricsObject <- list()
      if (!is.null(self$`impression_count`)) {
        TweetPromotedMetricsObject[["impression_count"]] <-
          self$`impression_count`
      }
      if (!is.null(self$`like_count`)) {
        TweetPromotedMetricsObject[["like_count"]] <-
          self$`like_count`
      }
      if (!is.null(self$`reply_count`)) {
        TweetPromotedMetricsObject[["reply_count"]] <-
          self$`reply_count`
      }
      if (!is.null(self$`retweet_count`)) {
        TweetPromotedMetricsObject[["retweet_count"]] <-
          self$`retweet_count`
      }

      TweetPromotedMetricsObject
    },
    #' Deserialize JSON string into an instance of TweetPromotedMetrics
    #'
    #' @description
    #' Deserialize JSON string into an instance of TweetPromotedMetrics
    #'
    #' @param input_json the JSON input
    #' @return the instance of TweetPromotedMetrics
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`impression_count`)) {
        self$`impression_count` <- this_object$`impression_count`
      }
      if (!is.null(this_object$`like_count`)) {
        self$`like_count` <- this_object$`like_count`
      }
      if (!is.null(this_object$`reply_count`)) {
        self$`reply_count` <- this_object$`reply_count`
      }
      if (!is.null(this_object$`retweet_count`)) {
        self$`retweet_count` <- this_object$`retweet_count`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return TweetPromotedMetrics in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`impression_count`)) {
          sprintf(
          '"impression_count":
            %d
                    ',
          self$`impression_count`
          )
        },
        if (!is.null(self$`like_count`)) {
          sprintf(
          '"like_count":
            %d
                    ',
          self$`like_count`
          )
        },
        if (!is.null(self$`reply_count`)) {
          sprintf(
          '"reply_count":
            %d
                    ',
          self$`reply_count`
          )
        },
        if (!is.null(self$`retweet_count`)) {
          sprintf(
          '"retweet_count":
            %d
                    ',
          self$`retweet_count`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of TweetPromotedMetrics
    #'
    #' @description
    #' Deserialize JSON string into an instance of TweetPromotedMetrics
    #'
    #' @param input_json the JSON input
    #' @return the instance of TweetPromotedMetrics
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`impression_count` <- this_object$`impression_count`
      self$`like_count` <- this_object$`like_count`
      self$`reply_count` <- this_object$`reply_count`
      self$`retweet_count` <- this_object$`retweet_count`
      self
    },
    #' Validate JSON input with respect to TweetPromotedMetrics
    #'
    #' @description
    #' Validate JSON input with respect to TweetPromotedMetrics and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of TweetPromotedMetrics
    #' @export
    toString = function() {
      self$toJSONString()
    }
  )
)
