#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title TweetComplianceSchemaTweet
#' @description TweetComplianceSchemaTweet Class
#' @format An \code{R6Class} generator object
#' @field author_id  character
#' @field id  character
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TweetComplianceSchemaTweet <- R6::R6Class(
  "TweetComplianceSchemaTweet",
  public = list(
    `author_id` = NULL,
    `id` = NULL,
    #' Initialize a new TweetComplianceSchemaTweet class.
    #'
    #' @description
    #' Initialize a new TweetComplianceSchemaTweet class.
    #'
    #' @param author_id Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
    #' @param id Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `author_id`, `id`, ...
    ) {
      if (!missing(`author_id`)) {
        stopifnot(is.character(`author_id`), length(`author_id`) == 1)
        self$`author_id` <- `author_id`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return TweetComplianceSchemaTweet in JSON format
    #' @export
    toJSON = function() {
      TweetComplianceSchemaTweetObject <- list()
      if (!is.null(self$`author_id`)) {
        TweetComplianceSchemaTweetObject[["author_id"]] <-
          self$`author_id`
      }
      if (!is.null(self$`id`)) {
        TweetComplianceSchemaTweetObject[["id"]] <-
          self$`id`
      }

      TweetComplianceSchemaTweetObject
    },
    #' Deserialize JSON string into an instance of TweetComplianceSchemaTweet
    #'
    #' @description
    #' Deserialize JSON string into an instance of TweetComplianceSchemaTweet
    #'
    #' @param input_json the JSON input
    #' @return the instance of TweetComplianceSchemaTweet
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`author_id`)) {
        self$`author_id` <- this_object$`author_id`
      }
      if (!is.null(this_object$`id`)) {
        self$`id` <- this_object$`id`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return TweetComplianceSchemaTweet in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`author_id`)) {
          sprintf(
          '"author_id":
            "%s"
                    ',
          self$`author_id`
          )
        },
        if (!is.null(self$`id`)) {
          sprintf(
          '"id":
            "%s"
                    ',
          self$`id`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of TweetComplianceSchemaTweet
    #'
    #' @description
    #' Deserialize JSON string into an instance of TweetComplianceSchemaTweet
    #'
    #' @param input_json the JSON input
    #' @return the instance of TweetComplianceSchemaTweet
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`author_id` <- this_object$`author_id`
      self$`id` <- this_object$`id`
      self
    },
    #' Validate JSON input with respect to TweetComplianceSchemaTweet
    #'
    #' @description
    #' Validate JSON input with respect to TweetComplianceSchemaTweet and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `author_id`
      if (!is.null(input_json$`author_id`)) {
        stopifnot(is.character(input_json$`author_id`), length(input_json$`author_id`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for TweetComplianceSchemaTweet: the required field `author_id` is missing."))
      }
      # check the required field `id`
      if (!is.null(input_json$`id`)) {
        stopifnot(is.character(input_json$`id`), length(input_json$`id`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for TweetComplianceSchemaTweet: the required field `id` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of TweetComplianceSchemaTweet
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      # check if the required `author_id` is null
      if (is.null(self$`author_id`)) {
        return(FALSE)
      }

      if (!str_detect(self$`author_id`, "^[0-9]{1,19}$")) {
        return(FALSE)
      }

      # check if the required `id` is null
      if (is.null(self$`id`)) {
        return(FALSE)
      }

      if (!str_detect(self$`id`, "^[0-9]{1,19}$")) {
        return(FALSE)
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      # check if the required `author_id` is null
      if (is.null(self$`author_id`)) {
        invalid_fields["author_id"] = "Non-nullable required field `author_id` cannot be null."
      }

      if (!str_detect(self$`author_id`, "^[0-9]{1,19}$")) {
        invalid_fields["author_id"] = "Invalid value for `author_id`, must conform to the pattern ^[0-9]{1,19}$."
      }

      # check if the required `id` is null
      if (is.null(self$`id`)) {
        invalid_fields["id"] = "Non-nullable required field `id` cannot be null."
      }

      if (!str_detect(self$`id`, "^[0-9]{1,19}$")) {
        invalid_fields["id"] = "Invalid value for `id`, must conform to the pattern ^[0-9]{1,19}$."
      }

      invalid_fields
    }
  )
)

