#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title UsageCapExceededProblemAllOf
#' @description UsageCapExceededProblemAllOf Class
#' @format An \code{R6Class} generator object
#' @field period  character [optional]
#' @field scope  character [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UsageCapExceededProblemAllOf <- R6::R6Class(
  "UsageCapExceededProblemAllOf",
  public = list(
    `period` = NULL,
    `scope` = NULL,
    #' Initialize a new UsageCapExceededProblemAllOf class.
    #'
    #' @description
    #' Initialize a new UsageCapExceededProblemAllOf class.
    #'
    #' @param period period
    #' @param scope scope
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `period` = NULL, `scope` = NULL, ...
    ) {
      if (!is.null(`period`)) {
        stopifnot(is.character(`period`), length(`period`) == 1)
        self$`period` <- `period`
      }
      if (!is.null(`scope`)) {
        stopifnot(is.character(`scope`), length(`scope`) == 1)
        self$`scope` <- `scope`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return UsageCapExceededProblemAllOf in JSON format
    #' @export
    toJSON = function() {
      UsageCapExceededProblemAllOfObject <- list()
      if (!is.null(self$`period`)) {
        UsageCapExceededProblemAllOfObject[["period"]] <-
          self$`period`
      }
      if (!is.null(self$`scope`)) {
        UsageCapExceededProblemAllOfObject[["scope"]] <-
          self$`scope`
      }

      UsageCapExceededProblemAllOfObject
    },
    #' Deserialize JSON string into an instance of UsageCapExceededProblemAllOf
    #'
    #' @description
    #' Deserialize JSON string into an instance of UsageCapExceededProblemAllOf
    #'
    #' @param input_json the JSON input
    #' @return the instance of UsageCapExceededProblemAllOf
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`period`)) {
        self$`period` <- this_object$`period`
      }
      if (!is.null(this_object$`scope`)) {
        self$`scope` <- this_object$`scope`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return UsageCapExceededProblemAllOf in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`period`)) {
          sprintf(
          '"period":
            "%s"
                    ',
          self$`period`
          )
        },
        if (!is.null(self$`scope`)) {
          sprintf(
          '"scope":
            "%s"
                    ',
          self$`scope`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of UsageCapExceededProblemAllOf
    #'
    #' @description
    #' Deserialize JSON string into an instance of UsageCapExceededProblemAllOf
    #'
    #' @param input_json the JSON input
    #' @return the instance of UsageCapExceededProblemAllOf
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`period` <- this_object$`period`
      self$`scope` <- this_object$`scope`
      self
    },
    #' Validate JSON input with respect to UsageCapExceededProblemAllOf
    #'
    #' @description
    #' Validate JSON input with respect to UsageCapExceededProblemAllOf and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of UsageCapExceededProblemAllOf
    #' @export
    toString = function() {
      self$toJSONString()
    }
  )
)
