#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title UserDeleteComplianceSchema
#' @description UserDeleteComplianceSchema Class
#' @format An \code{R6Class} generator object
#' @field user_delete  \link{UserComplianceSchema}
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserDeleteComplianceSchema <- R6::R6Class(
  "UserDeleteComplianceSchema",
  public = list(
    `user_delete` = NULL,
    #' Initialize a new UserDeleteComplianceSchema class.
    #'
    #' @description
    #' Initialize a new UserDeleteComplianceSchema class.
    #'
    #' @param user_delete user_delete
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `user_delete`, ...
    ) {
      if (!missing(`user_delete`)) {
        stopifnot(R6::is.R6(`user_delete`))
        self$`user_delete` <- `user_delete`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return UserDeleteComplianceSchema in JSON format
    #' @export
    toJSON = function() {
      UserDeleteComplianceSchemaObject <- list()
      if (!is.null(self$`user_delete`)) {
        UserDeleteComplianceSchemaObject[["user_delete"]] <-
          self$`user_delete`$toJSON()
      }

      UserDeleteComplianceSchemaObject
    },
    #' Deserialize JSON string into an instance of UserDeleteComplianceSchema
    #'
    #' @description
    #' Deserialize JSON string into an instance of UserDeleteComplianceSchema
    #'
    #' @param input_json the JSON input
    #' @return the instance of UserDeleteComplianceSchema
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`user_delete`)) {
        user_delete_object <- UserComplianceSchema$new()
        user_delete_object$fromJSON(jsonlite::toJSON(this_object$user_delete, auto_unbox = TRUE, digits = NA))
        self$`user_delete` <- user_delete_object
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return UserDeleteComplianceSchema in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`user_delete`)) {
          sprintf(
          '"user_delete":
          %s
          ',
          jsonlite::toJSON(self$`user_delete`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of UserDeleteComplianceSchema
    #'
    #' @description
    #' Deserialize JSON string into an instance of UserDeleteComplianceSchema
    #'
    #' @param input_json the JSON input
    #' @return the instance of UserDeleteComplianceSchema
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`user_delete` <- UserComplianceSchema$new()$fromJSON(jsonlite::toJSON(this_object$user_delete, auto_unbox = TRUE, digits = NA))
      self
    },
    #' Validate JSON input with respect to UserDeleteComplianceSchema
    #'
    #' @description
    #' Validate JSON input with respect to UserDeleteComplianceSchema and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `user_delete`
      if (!is.null(input_json$`user_delete`)) {
        stopifnot(R6::is.R6(input_json$`user_delete`))
      } else {
        stop(paste("The JSON input `", input, "` is invalid for UserDeleteComplianceSchema: the required field `user_delete` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of UserDeleteComplianceSchema
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      # check if the required `user_delete` is null
      if (is.null(self$`user_delete`)) {
        FALSE
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      # check if the required `user_delete` is null
      if (is.null(self$`user_delete`)) {
        invalid_fields["user_delete"] <- "Non-nullable required field `user_delete` cannot be null."
      }

      invalid_fields
    }
  )
)
