#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title UsersFollowingDeleteResponse
#' @description UsersFollowingDeleteResponse Class
#' @format An \code{R6Class} generator object
#' @field data  \link{ListFollowedResponseData} [optional]
#' @field errors  list( \link{Problem} ) [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UsersFollowingDeleteResponse <- R6::R6Class(
  "UsersFollowingDeleteResponse",
  public = list(
    `data` = NULL,
    `errors` = NULL,
    #' Initialize a new UsersFollowingDeleteResponse class.
    #'
    #' @description
    #' Initialize a new UsersFollowingDeleteResponse class.
    #'
    #' @param data data
    #' @param errors errors
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `data` = NULL, `errors` = NULL, ...
    ) {
      if (!is.null(`data`)) {
        stopifnot(R6::is.R6(`data`))
        self$`data` <- `data`
      }
      if (!is.null(`errors`)) {
        stopifnot(is.vector(`errors`), length(`errors`) != 0)
        sapply(`errors`, function(x) stopifnot(R6::is.R6(x)))
        self$`errors` <- `errors`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return UsersFollowingDeleteResponse in JSON format
    #' @export
    toJSON = function() {
      UsersFollowingDeleteResponseObject <- list()
      if (!is.null(self$`data`)) {
        UsersFollowingDeleteResponseObject[["data"]] <-
          self$`data`$toJSON()
      }
      if (!is.null(self$`errors`)) {
        UsersFollowingDeleteResponseObject[["errors"]] <-
          lapply(self$`errors`, function(x) x$toJSON())
      }

      UsersFollowingDeleteResponseObject
    },
    #' Deserialize JSON string into an instance of UsersFollowingDeleteResponse
    #'
    #' @description
    #' Deserialize JSON string into an instance of UsersFollowingDeleteResponse
    #'
    #' @param input_json the JSON input
    #' @return the instance of UsersFollowingDeleteResponse
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`data`)) {
        data_object <- ListFollowedResponseData$new()
        data_object$fromJSON(jsonlite::toJSON(this_object$data, auto_unbox = TRUE, digits = NA))
        self$`data` <- data_object
      }
      if (!is.null(this_object$`errors`)) {
        self$`errors` <- ApiClient$new()$deserializeObj(this_object$`errors`, "array[Problem]", loadNamespace("twitter"))
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return UsersFollowingDeleteResponse in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`data`)) {
          sprintf(
          '"data":
          %s
          ',
          jsonlite::toJSON(self$`data`$toJSON(), auto_unbox = TRUE, digits = NA)
          )
        },
        if (!is.null(self$`errors`)) {
          sprintf(
          '"errors":
          [%s]
',
          paste(sapply(self$`errors`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of UsersFollowingDeleteResponse
    #'
    #' @description
    #' Deserialize JSON string into an instance of UsersFollowingDeleteResponse
    #'
    #' @param input_json the JSON input
    #' @return the instance of UsersFollowingDeleteResponse
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`data` <- ListFollowedResponseData$new()$fromJSON(jsonlite::toJSON(this_object$data, auto_unbox = TRUE, digits = NA))
      self$`errors` <- ApiClient$new()$deserializeObj(this_object$`errors`, "array[Problem]", loadNamespace("twitter"))
      self
    },
    #' Validate JSON input with respect to UsersFollowingDeleteResponse
    #'
    #' @description
    #' Validate JSON input with respect to UsersFollowingDeleteResponse and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of UsersFollowingDeleteResponse
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      if (length(`errors`) < 1) {
        FALSE
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      if (length(`errors`) < 1) {
        invalid_fields[`errors`] = "Invalid length for ``, number of items must be greater than or equal to 1."
      }

      invalid_fields
    }
  )
)
