#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title UsersRetweetsCreateRequest
#' @description UsersRetweetsCreateRequest Class
#' @format An \code{R6Class} generator object
#' @field tweet_id  character
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UsersRetweetsCreateRequest <- R6::R6Class(
  "UsersRetweetsCreateRequest",
  public = list(
    `tweet_id` = NULL,
    #' Initialize a new UsersRetweetsCreateRequest class.
    #'
    #' @description
    #' Initialize a new UsersRetweetsCreateRequest class.
    #'
    #' @param tweet_id Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `tweet_id`, ...
    ) {
      if (!missing(`tweet_id`)) {
        stopifnot(is.character(`tweet_id`), length(`tweet_id`) == 1)
        self$`tweet_id` <- `tweet_id`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return UsersRetweetsCreateRequest in JSON format
    #' @export
    toJSON = function() {
      UsersRetweetsCreateRequestObject <- list()
      if (!is.null(self$`tweet_id`)) {
        UsersRetweetsCreateRequestObject[["tweet_id"]] <-
          self$`tweet_id`
      }

      UsersRetweetsCreateRequestObject
    },
    #' Deserialize JSON string into an instance of UsersRetweetsCreateRequest
    #'
    #' @description
    #' Deserialize JSON string into an instance of UsersRetweetsCreateRequest
    #'
    #' @param input_json the JSON input
    #' @return the instance of UsersRetweetsCreateRequest
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`tweet_id`)) {
        self$`tweet_id` <- this_object$`tweet_id`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return UsersRetweetsCreateRequest in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`tweet_id`)) {
          sprintf(
          '"tweet_id":
            "%s"
                    ',
          self$`tweet_id`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of UsersRetweetsCreateRequest
    #'
    #' @description
    #' Deserialize JSON string into an instance of UsersRetweetsCreateRequest
    #'
    #' @param input_json the JSON input
    #' @return the instance of UsersRetweetsCreateRequest
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`tweet_id` <- this_object$`tweet_id`
      self
    },
    #' Validate JSON input with respect to UsersRetweetsCreateRequest
    #'
    #' @description
    #' Validate JSON input with respect to UsersRetweetsCreateRequest and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
      # check the required field `tweet_id`
      if (!is.null(input_json$`tweet_id`)) {
        stopifnot(is.character(input_json$`tweet_id`), length(input_json$`tweet_id`) == 1)
      } else {
        stop(paste("The JSON input `", input, "` is invalid for UsersRetweetsCreateRequest: the required field `tweet_id` is missing."))
      }
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of UsersRetweetsCreateRequest
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      # check if the required `tweet_id` is null
      if (is.null(self$`tweet_id`)) {
        return(FALSE)
      }

      if (!str_detect(self$`tweet_id`, "^[0-9]{1,19}$")) {
        return(FALSE)
      }

      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      # check if the required `tweet_id` is null
      if (is.null(self$`tweet_id`)) {
        invalid_fields["tweet_id"] = "Non-nullable required field `tweet_id` cannot be null."
      }

      if (!str_detect(self$`tweet_id`, "^[0-9]{1,19}$")) {
        invalid_fields["tweet_id"] = "Invalid value for `tweet_id`, must conform to the pattern ^[0-9]{1,19}$."
      }

      invalid_fields
    }
  )
)

