#' Twitter API v2
#'
#' Twitter API v2 available endpoints
#'
#' The version of the OpenAPI document: 2.49
#' Generated by: https://openapi-generator.tech
#'

#' @docType class
#' @title VideoAllOfNonPublicMetrics
#' @description VideoAllOfNonPublicMetrics Class
#' @format An \code{R6Class} generator object
#' @field playback_0_count  integer [optional]
#' @field playback_100_count  integer [optional]
#' @field playback_25_count  integer [optional]
#' @field playback_50_count  integer [optional]
#' @field playback_75_count  integer [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VideoAllOfNonPublicMetrics <- R6::R6Class(
  "VideoAllOfNonPublicMetrics",
  public = list(
    `playback_0_count` = NULL,
    `playback_100_count` = NULL,
    `playback_25_count` = NULL,
    `playback_50_count` = NULL,
    `playback_75_count` = NULL,
    #' Initialize a new VideoAllOfNonPublicMetrics class.
    #'
    #' @description
    #' Initialize a new VideoAllOfNonPublicMetrics class.
    #'
    #' @param playback_0_count Number of users who made it through 0% of the video.
    #' @param playback_100_count Number of users who made it through 100% of the video.
    #' @param playback_25_count Number of users who made it through 25% of the video.
    #' @param playback_50_count Number of users who made it through 50% of the video.
    #' @param playback_75_count Number of users who made it through 75% of the video.
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(
        `playback_0_count` = NULL, `playback_100_count` = NULL, `playback_25_count` = NULL, `playback_50_count` = NULL, `playback_75_count` = NULL, ...
    ) {
      if (!is.null(`playback_0_count`)) {
        stopifnot(is.numeric(`playback_0_count`), length(`playback_0_count`) == 1)
        self$`playback_0_count` <- `playback_0_count`
      }
      if (!is.null(`playback_100_count`)) {
        stopifnot(is.numeric(`playback_100_count`), length(`playback_100_count`) == 1)
        self$`playback_100_count` <- `playback_100_count`
      }
      if (!is.null(`playback_25_count`)) {
        stopifnot(is.numeric(`playback_25_count`), length(`playback_25_count`) == 1)
        self$`playback_25_count` <- `playback_25_count`
      }
      if (!is.null(`playback_50_count`)) {
        stopifnot(is.numeric(`playback_50_count`), length(`playback_50_count`) == 1)
        self$`playback_50_count` <- `playback_50_count`
      }
      if (!is.null(`playback_75_count`)) {
        stopifnot(is.numeric(`playback_75_count`), length(`playback_75_count`) == 1)
        self$`playback_75_count` <- `playback_75_count`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return VideoAllOfNonPublicMetrics in JSON format
    #' @export
    toJSON = function() {
      VideoAllOfNonPublicMetricsObject <- list()
      if (!is.null(self$`playback_0_count`)) {
        VideoAllOfNonPublicMetricsObject[["playback_0_count"]] <-
          self$`playback_0_count`
      }
      if (!is.null(self$`playback_100_count`)) {
        VideoAllOfNonPublicMetricsObject[["playback_100_count"]] <-
          self$`playback_100_count`
      }
      if (!is.null(self$`playback_25_count`)) {
        VideoAllOfNonPublicMetricsObject[["playback_25_count"]] <-
          self$`playback_25_count`
      }
      if (!is.null(self$`playback_50_count`)) {
        VideoAllOfNonPublicMetricsObject[["playback_50_count"]] <-
          self$`playback_50_count`
      }
      if (!is.null(self$`playback_75_count`)) {
        VideoAllOfNonPublicMetricsObject[["playback_75_count"]] <-
          self$`playback_75_count`
      }

      VideoAllOfNonPublicMetricsObject
    },
    #' Deserialize JSON string into an instance of VideoAllOfNonPublicMetrics
    #'
    #' @description
    #' Deserialize JSON string into an instance of VideoAllOfNonPublicMetrics
    #'
    #' @param input_json the JSON input
    #' @return the instance of VideoAllOfNonPublicMetrics
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`playback_0_count`)) {
        self$`playback_0_count` <- this_object$`playback_0_count`
      }
      if (!is.null(this_object$`playback_100_count`)) {
        self$`playback_100_count` <- this_object$`playback_100_count`
      }
      if (!is.null(this_object$`playback_25_count`)) {
        self$`playback_25_count` <- this_object$`playback_25_count`
      }
      if (!is.null(this_object$`playback_50_count`)) {
        self$`playback_50_count` <- this_object$`playback_50_count`
      }
      if (!is.null(this_object$`playback_75_count`)) {
        self$`playback_75_count` <- this_object$`playback_75_count`
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return VideoAllOfNonPublicMetrics in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`playback_0_count`)) {
          sprintf(
          '"playback_0_count":
            %d
                    ',
          self$`playback_0_count`
          )
        },
        if (!is.null(self$`playback_100_count`)) {
          sprintf(
          '"playback_100_count":
            %d
                    ',
          self$`playback_100_count`
          )
        },
        if (!is.null(self$`playback_25_count`)) {
          sprintf(
          '"playback_25_count":
            %d
                    ',
          self$`playback_25_count`
          )
        },
        if (!is.null(self$`playback_50_count`)) {
          sprintf(
          '"playback_50_count":
            %d
                    ',
          self$`playback_50_count`
          )
        },
        if (!is.null(self$`playback_75_count`)) {
          sprintf(
          '"playback_75_count":
            %d
                    ',
          self$`playback_75_count`
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of VideoAllOfNonPublicMetrics
    #'
    #' @description
    #' Deserialize JSON string into an instance of VideoAllOfNonPublicMetrics
    #'
    #' @param input_json the JSON input
    #' @return the instance of VideoAllOfNonPublicMetrics
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`playback_0_count` <- this_object$`playback_0_count`
      self$`playback_100_count` <- this_object$`playback_100_count`
      self$`playback_25_count` <- this_object$`playback_25_count`
      self$`playback_50_count` <- this_object$`playback_50_count`
      self$`playback_75_count` <- this_object$`playback_75_count`
      self
    },
    #' Validate JSON input with respect to VideoAllOfNonPublicMetrics
    #'
    #' @description
    #' Validate JSON input with respect to VideoAllOfNonPublicMetrics and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of VideoAllOfNonPublicMetrics
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      invalid_fields
    }
  )
)

